### ISSUE TITLE
Optional Chaining vs Implicit Unwrapping

### ISSUE THREAD

**Issue by aaronpang** [raywenderlich/swift-style-guide#106]
After following a few tutorials on Swift I've noticed that there seems to be a lot of usage involving nil checks and implicit unwraps. For example, I've seen examples such as:
```swift
var bar: Int? = 0
if bar == nil {
  print(bar!)
}
```
As opposed to doing:
```swift
var bar: Int? = 0
if let unwrappedBar = bar {
  print(unwrappedBar)
}
```
I'm wondering if there should be a section regarding which one should be used and why? I guess this is a style guide rather than correct coding conventions guide so perhaps this is irrelevant.

**Comment by yomajkel** [comment]
One point here is that when 
```
if let unwrappedBar = bar
```
makes a copy, and I believe it does (not 100% sure about it, but it has to be copied to guarantee it is a constant), this would be a thread safe version.

**Comment by kassisdion** [comment]
It depend on your vision of things

* Sometimes you want to work by inclusion 
```swift

//use this
if let list = self.list where list.count == 3,
    let first = list[0] as? CGFloat,
    let second = list[1] as? CGFloat,
    let third = list[2] as? CGFloat  {
        //Do what you want everythink is ok
}

//instead of this ugly version
if let list = nil where list.count == 3 {
    if let first = list[0] as? CGFloat {
        if let second = list[1] as? CGFloat {
            if let third = list[2] as? CGFloat {
            //Do what you want everythink is ok
            }
        }
    }
}
```

* And sometimes you want to work by exclusion

I advice you this article http://code.tutsplus.com/tutorials/swift-20-exit-early-with-guard--cms-24326 which explain how to work by exclusion
```swift
//check for initial condition
if !list { return }
if list.count =! 3 { return }

//get entities
let first = list[0] as? CGFloat
let second = list[1] as? CGFloat
let third = list[2] as? CGFloat

//check entities
if !first { return }
if !second { return }
if !third { return }

//Do what you want everythink is ok
```

**Comment by hollance** [comment]
A lot of people writing Swift code are bringing habits from other languages that do not have `if let`. So if you're used to writing `if bar == nil` then you might be tempted to keep writing this even in Swift. 

Now that Swift 2.0 is around the corner, the new `guard` statement should put an end to this. :-)

**Comment by kassisdion** [comment]
I find the exclusion method more readable and maintainable (i see so much ugly and unmaintainable due to if chaining... )  that's why i've made a link to http://code.tutsplus.com/tutorials/swift-20-exit-early-with-guard--cms-24326 cause he explain the Guard statement and how to ''good'' use it :D

**Comment by aaronpang** [comment]
So my take from this is that one should never use the ```if bar == nil``` check and always use a optional binding whether it be an ```if let unwrappedBar = bar``` or ```guard let unwrappedBar = bar else``` depending on if one wants to work with inclusion or exclusion. Simply put, it's just bad habits people are carrying over from other languages to implicitly unwrap objects after a nil check - correct me if I'm wrong? I guess this would be more of a Swift 2.0 style preference then.
