### ISSUE TITLE
Using underscore for long numbers

### ISSUE THREAD

**Issue by cristeahub** [raywenderlich/swift-style-guide#108]
If a number is very long, say `1000000`, swift allows us to write that numbers as `1_000_000`.

This way of writing numbers has been proved useful at least for me. I suggest adding it to the style guide.

**Comment by edekhayser** [comment]
I can't remember seeing any tutorials on raywenderlich.com that include numbers that would call for underscores. This style guide is meant to improve content on the site and in books, and while this style may be helpful elsewhere, I don't think it is important enough to specify in the style guide.

**Comment by cristeahub** [comment]
Sure I understand that, however this could introduce bigger numbers, which one will face when programming. Even `1_000` will help distinguish it from `100`. Having this in the style guide now will mean it can be used as soon as it's needed.

**Comment by marcinmatczuk** [comment]
Underscores are all fun, but Swift compiler will also allow `1_0_0_000_0` for representing `1_000_000` - misuse is quite easy.
If underscores are to be allowed in any kind of style guide, the usage rule would need to sanction/enforce proper grouping. Just my two cents (I'm not affiliated with `raywenderlich.com`)

**Comment by andypye** [comment]
I think it would be handy, but stipulate that it follows the real world usage with commas after 
eg. 1,000,000 becomes 1_000_000



On 29 Jul 2015, at 5:00 pm, Marcin Matczuk <notifications@github.com> wrote:

Underscores are all fun, but Swift compiler will also allow 1_0_0_000_0 for representing 1_000_000 - misuse is quite easy.
If underscores are to be allowed in any kind of style guide, the usage rule would need to sanction/enforce proper grouping. Just my two cents (I'm not affiliated with raywenderlich.com)

**Comment by cristeahub** [comment]
Adding a clause that it the number separators should only be used to separate full 1000's could be beneficial, yes.

**Comment by Jessy-** [comment]
The underscore has uses outside of decimal:
```swift
0b10_0000_0001 // 513
0xFF_00_FF // magenta, in 1-byte-per-channel RGB

**Comment by JRG-Developer** [comment]
> I can't remember seeing any tutorials on raywenderlich.com that include numbers that would call for underscores. This style guide is meant to improve content on the site and in books, and while this style may be helpful elsewhere, I don't think it is important enough to specify in the style guide. That is just my opinion, others may feel differently.

I agree with Evan here.

**Comment by rayfix** [comment]
Yes. I think it is a rare enough case for the tutorial / book world where I don't feel like we should enforce a style standard.  That doesn't mean it isn't a useful tool to have!
