### ISSUE TITLE
Closures style in chained methods call

### ISSUE THREAD

**Issue by kostiakoval** [raywenderlich/swift-style-guide#110]
Should we use trading closure syntax or not? Where to put spaces and etc :)

Example
`numbers.map { $0 * 2 }.filter { $0 % 3 == 0 }.indexOf(90)`
http://www.raywenderlich.com/108522/whats-new-in-swift-2

Vs
`Array(1...5).map({$0 * 2}).forEach{print($0)}`
http://ericasadun.com/2015/08/06/jive-with-beta-five-swiftlang/

**Comment by kostiakoval** [comment]
I was playing around with the syntax, here are few examples

```swift
let ar = [1, 200, 400]

//v1
ar.map { $0 * 2 }.filter { $0 > 50 }.map { $0 + 10 }

//v1.1
ar.map {$0 * 2}.filter {$0 > 50}.map {$0 + 10}
// The method and the closure is separated by space. 
// Looks like {$0 * 2}.filter is related to filter not the map

//v1.2
ar.map({ $0 * 2 }).filter({ $0 > 50 }).map({ $0 + 10 })

//v2
ar.map { $0 * 2 } .filter { $0 > 50 } .map { $0 + 10 }
// Even more horrible

//v3
ar.map{ $0 * 2 } .filter{ $0 > 50 } .map{ $0 + 10 }
//Now it's clear that { $0 * 2 } closure is related to map

//v4
ar.map{$0 * 2} .filter{$0 > 50} .map{$0 + 10}
// Better with whitespaces

//v5
ar.map  { $0 * 2 }
  .filter { $0 > 50 }
  .map { $0 + 10 }
```

**Comment by RobertGummesson** [comment]
Had to check what I do and it turned out to be either v1 or one that wasn't in the list so I'll just add it here. My personal preference is v1 so I should really refactor my own code to keep it consistent. :)
```
//v6
ar.map{ $0 * 2 }.filter{ $0 > 50 }.map{ $0 + 10 }
```

**Comment by kostiakoval** [comment]
I was also thinking of that v6 solution. 
For simple functions with 1 trailing closure I use v1 `ar.map { $0 * 2 }`
But when there are chained calls v1 is not so clear, as for me. I would prefer v6. 
Also I've asked few people and they like v5 the most

**Comment by Jessy-** [comment]
This was not shown as an option above, but what I've been using.
```swift
ar.map{$0 * 2}.filter{$0 > 50}.map{$0 + 10}

ar
.map{$0 * 2}
.filter{$0 > 50}
.map{$0 + 10}
.forEach{print($0)}

let identForAssignement = ar
   .map{$0 * 2}
   .filter{$0 > 50}
   .map{$0 + 10}

**Comment by rayfix** [comment]
I like v1.1 the best.  The question is, does this kind of thing occur often enough in tutorials to try to standardize on.

**Comment by JRG-Developer** [comment]
I don't think it's worthwhile to have a standard on this:

Reasoning:

1. I don't think this occurs very often, at least not more than 2 chained together.
1. It would be difficult to catch inconsistencies (considering everything else we're already looking for as well), and I don't think there's a great benefit here.

To me, the root issue is "chained methods should be clear and easy to read in context."

Depending on context, this may mean putting them on the same line, breaking on cross lines, or a combination of such.
