### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by lfaoro** [raywenderlich/swift-style-guide#112]
I see there's no code organization like in the [ObjC](https://github.com/raywenderlich/objective-c-style-guide#code-organization) style guide, would be possible to have a code organization guideline for Swift. I currently use something similar to the ObjC one with `//MARK:- `

**Comment by krishnkishore** [comment]
// MARK: (As with #pragma, marks followed by a single dash (-) will be preceded with a horizontal divider)
// TODO:
// FIXME:

**Comment by rayfix** [comment]
Hi.  Taking over maintenance of the style guide.  Thanks for your input.  There is mention of using Mark: but I will expand on it in a future update.
