### ISSUE TITLE
Class vs instance short notation

### ISSUE THREAD

**Issue by fritza** [raywenderlich/swift-style-guide#113]
My issue is not about code but identifying `class` (etc.) symbols in prose, such as in `README`s, tutorials, and comments. Everything here is based on what I’ve observed, which may come of my poor choice of search terms.

In Objective-C, it’s easy to identify class methods versus instance in prose:

```Objective-C
// My opinions, not having read the raywenderlich style guide

+ [MyClass initialize]
- [MyClass deflagrate]
- [MyClass resize:metric:]

// Properties belong to instances, so there’s no ambiguity in
MyClass.count

// But if you’re discussing a method that implements a property,
// the rule should be the same as for any other method
- [MyClass count]
- [MyClass setCount:]
```

I haven’t seen any way to distinguish the two when referring in prose to the same in Swift.

```Swift
// “class” entity includes struct/enum; “class” qualifier includes static

MyClass.initialize()         // class or instance?
MyClass.deflagrate()    // class or instance?
MyClass.resize(_:, metric:)  // class or instance?
MyClass.description    // class or instance?
MyClass.maximumCount // class var or let — new problem in Swift

// Properties don’t have quite the same problem…
MyClass.count { get set } //  per the example of generated interfaces.
    // What if you want a notation distinguishing
    // `get`, `set`, `didSet`, `willSet`? MyClass.count { get } implies a
    // read-only property.
```

Must one translate back to Objective-C notation? That’s no help in the case of the observed-property closures. One reason Swift exists is to express things Objective-C can’t; we can expect more examples in the future.

Following the example of the jump bar doesn’t help. It doesn’t make any distinction, nor even list `static` / `class` constants.

Maybe my Googling skills are inadequate. If so I apologize. But I’ve never seen a solution, and a style guide may be a good place to set a standard.

### Aside

This is a quibble that I’m reluctant to make a separate issue of:

If you break a `func` declaration (or `if-let-where`… there are others) into two or more lines, and append the opening `{` to the last of those lines, Xcode will indent the body one step further than suits the new scope. This is a waste of space, and misleads the reader about the nesting level. I’d rather not pay the price of fighting automatic indentation just to conform to a generally-wise coding convention. I put the opening brace `<mutter>`_all_ braces are “curly”`</mutter>` on a new line in that case.

**Comment by fritza** [comment]
Amended Swift-notation `initialize` to `initialize()`.

**Comment by rayfix** [comment]
Hi!  Thanks for your thoughts.  I just became maintainer of the style guide and was looking through some of the neglected issues.

The style guide mandates that instances are lowerCamelCase while model types (class, struct, enum) are UpperCamelCase.  This makes it possible to distinguish static methods at the call site.

```swift
myClass.count  // must be an instance
MyClass.count // must be a static
``` 
It probably makes sense to file a radar on the Xcode jump bar.  

In the interface itself is marked with static (or class in the generated API view).  Maybe it is not as easy to see as Objective-C's + and - but the distinction is there.  

With regard to the aside about indenting and long lines, I am not seeing that issue in Xcode 7.3.  (I don't remember a time seeing it but it is possible I didn't understand you.)  It is probably unlikely that we will change the indentation style as so much precident already exists.  That said, feel free to fork the guide and turn it to what best suites your project's needs.

Thanks again for your participation and suggestions.
