### ISSUE TITLE
Optional binding for Arrays

### ISSUE THREAD

**Issue by LookingSharp** [raywenderlich/swift-style-guide#117]
The existing rules for optional binding result in clear safe code, but they break down with Value types that will result in a copy, like Arrays.  Have people found a good pattern to keep this code clean without checking for nil and using `!`, and without paying the penalty of an additional copy?

Here's an example, where I want to use an optional array to create another object.
```
class NumberHolder {
    init(nums: [Int]) { }
}

var arr: [Int]?
arr = [3, 4, 5]

if arr != nil {                       // ugly nil check
    var nh = NumberHolder(nums: arr!) // ugly !
}}
```

The problem with using `!` explicitly is that nil will result in a runtime crash instead of a compiler error.  The simple case above is unlikely to hit this, but sometimes the assumption is verified in a different place, and a refactor won't see this dependency.

Using the standard rules we get an additional copy.
```
if let arr = arr {                   // copy to create non-optional arr
    var nh = NumberHolder(nums: arr) // copy again to pass parameter
}
```

**Comment by gregheo** [comment]
Swift has copy-on-write and I'd expect this isn't an issue with optional binding. I haven't run the timings myself and can't prove it, but I believe in your example you won't get any copies since you're not mutating the array.

**Comment by LookingSharp** [comment]
Thanks Greg.  That makes sense.
