### ISSUE TITLE
Guidance on dictionary syntax omitted

### ISSUE THREAD

**Issue by arcseldon** [raywenderlich/swift-style-guide#122]
Excellent guidelines, thank you. 

However, I actually googled, and found these guidelines whilst trying to double check the preferred way to declare a dictionary literal in Swift, specifically whether there should be any spacing to the left of the colon. I appreciate you do discuss this with reference to named parameters etc, but please could you also do so for dictionaries. 

Being new to Swift, I was skimming through this simple tutorial: http://books.aidanf.net/learn-swift/dictionaries  where an example is given as:

```swift
var pets = ["Polly" : "dog", "Joey" : "goldfish"]
```
XCode's (limited) auto-format does not fix this. My understanding is that you would agree with having no space to the left of the colon, as follows:

```swift
var pets = ["Polly": "dog", "Joey": "goldfish"]
```

Correct?

**Comment by arcseldon** [comment]
Ok, I will concede that it is stated:

** Specify types for properties, variables, constants, argument declarations and other statements with a space after the colon but not before, e.g. x: Int, and Circle: Shape.**

Perhaps that could be expanded upon, with a few example scenarios? Thanks for considering this suggestion.

**Comment by rayfix** [comment]
Thanks for the suggestion!  I plan to include a section on left-magnetic-colons which is used by Apple Publications but not by the Swift standard library.  You can find some discussion on it here: http://ericasadun.com/2016/03/25/swift-colon-care-high-fiber-usage/
