### ISSUE TITLE
About the parameter in method

### ISSUE THREAD

**Issue by Guicai-Li** [raywenderlich/swift-style-guide#124]
In this swift-style-guide,I don't understand this line.
<pre>follow the standard Apple convention of referring to the first parameter in the method name</pre>
Could you explain this,please~  : ]

**Comment by JRG-Developer** [comment]
This means function signatures should refer to the first parameter. The guide specifically gives this example:

    class Counter {
      func combineWith(otherCounter: Counter, options: Dictionary?) { ... }
      func incrementBy(amount: Int) { ... }
    }

Both `with` and `by` refer to the first parameter. For example, they might be be used like this:

    let counter = Counter()
    let otherCounter = Counter()
    // ...

    counter.combineWith(otherCounter, options: nil)
    counter.incrementBy(42)

As you read this code, the meaning of `with` and `by` is obvious and easy to understand.

If multiple parameters are taken (especially of different types), it's also okay to list the name of the first parameter. Consider this `UIView` method for example:

    public class func animateWithDuration(duration: NSTimeInterval, animations: () -> Void)

which is used like this:

    UIView.animateWithDuration(1.0) {
        // ... animations...
    }

`withDuration` includes the name of the first parameter (`duration`) and in this case helps make the method easier to read.

**Comment by Guicai-Li** [comment]
thx

**Comment by basvankuijck** [comment]
This is not the case anymore with Swift 3.
If you take a look at the `Array`:

**Swift2:**
```
var ar = [ "string", "two", "three" ]
ar.removeAtIndex(1)
```

**Swift3:**
```
var ar = [ "string", "two", "three" ]
ar.remove(at: 1)
```

So according to this, this would turn into:
```
class Counter {
  func combine(with otherCounter: Counter, options: Dictionary?) { ... }
  func increment(by amount: Int) { ... }
}
```
and 
```
func date(fromString dateString: String) -> Date
```
