### ISSUE TITLE
To use or not to use parentheses 

### ISSUE THREAD

**Issue by bakku** [raywenderlich/swift-style-guide#126]
Should parentheses be used or not?

Example:

    var i = 0

    while i < 10 {
        print("Number \(i)")
        i += 1
    }

versus

    var i = 0

    while (i < 10) {
        print("Number \(i)")
        i += 1
    }

**Comment by konrado0905** [comment]
IMO should be use with more complex condition only

**Comment by Devxhkl** [comment]
I agree, it looks much cleaner to me w/o parentheses.

**Comment by mitchellporter** [comment]
+1 for no parentheses unless using a complex condition.

**Comment by chupakabr** [comment]
redundant, I'd rather go without parentheses, but depends on the situation, in case it's a long condition then parentheses might help

**Comment by flCer** [comment]
No parenthesis

**Comment by bakku** [comment]
Does a raywenderlich member update the style guide or does this happen via a pull request by me or somebody who feels responsible to do so?

**Comment by rayfix** [comment]
Hello @bakku Thank you for bringing this up.  I have just been assigned as the new maintainer of the style guide.    I think everyone is in agreement that no-parens is the way to go.  Of course, your particular example should be written with ```for i in 0..<10 { print("Number \(i)") } ``` but I digress. :)

**Comment by bakku** [comment]
Hello @rayfix. Will you update the style guide or should I create a PR ?

**Comment by rayfix** [comment]
I will add it as the guide is in a bit of organizational flux right now.  Thanks!
