### ISSUE TITLE
ID vs Id vs Identifier

### ISSUE THREAD

**Issue by jackwu95** [raywenderlich/swift-style-guide#129]
Examples:
```
var userID
var userId
var userIdentifier
```

I struggle with this about once per project and I don't see many discussions on it. 

I think it's _always_ a special case and as long as it's consistent within a project I try not to think about it too much.

However, would love to hear how others think and if there's _any_ logical advantage to any one of these options over the others.

**Comment by arctouch-ericchamberlain** [comment]
Apple appears to be favoring the identifier suffix, over the prior ID suffix.

Personally, I'm not a fan of the Id suffix.

**Comment by chupakabr** [comment]
I used to use camel case for abbreviations, so Id works for me. but if it's in the end of the name of a variable then ID is more readable i think

**Comment by jawwad** [comment]
Apple does use the "Identifier" suffix ex `reuseIdentifier`, `eventIdentifier` and when abbreviating Apple uses the uppercase "ID", for example `NSManagedObject` has an `objectID`, `CKNotification` has a `notificationID` and `subscriptionID`, `CKRecord` has a `createrUserRecordID` etc.

**Comment by mitchellporter** [comment]
I tend to stick to what @jawwad posted.

**Comment by rayfix** [comment]
@jawwad is correct. `userID` (The Dropbox SDK gets it wrong. :] ) 

Generally acronyms should be avoided but, The Apple API Design Guide says:

Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions:
```swift
var utf8Bytes: [UTF8.CodeUnit]
var isRepresentableAsASCII = true
var userSMTPServer: SecureSMTPServer
```

**Comment by rayfix** [comment]
Will include mention under naming.
