### ISSUE TITLE
Static variables 

### ISSUE THREAD

**Issue by GavinDBrown** [raywenderlich/swift-style-guide#131]
Not once is the word 'static' mentioned in the style guide.

```
class Carpet {
  static var potential = 0 // POTENTIAL?
  class func walkWithSocks() {
    Carpet.potential++
 }
}
```

Is this usage never prefered and `potential` should always be a global var?

**Comment by hollance** [comment]
`static` inside classes was added quite recently to Swift, IIRC, so maybe no one has thought to add it yet. :-)

That said, using `static` in a class is like using a global variable and has the same tradeoffs with regards to benefits and downsides.

**Comment by rayfix** [comment]
I plan to add some discussion on declaring constants which is a great usage of `static let`  As @hollance points out `static var` is essentially a global variable.

**Comment by rayfix** [comment]
Merged to the update branch.
