### ISSUE TITLE
About the name of UITableViewCell's reuseIdentifier and Segue's identifier

### ISSUE THREAD

**Issue by liuyubobobo** [raywenderlich/swift-style-guide#132]
I'm wondering how everybody named this two identifiers properly. I've seen so much different ways to name these identifiers in different tutorials or guildances. It seems that there's no discuss about them. I think these identifier's names should also have their own styles.

Here is my ideas:

The UITableViewCell's identifier is pointed to a noun - the Table View Cell, it is another name of the  Cell, so I always give it the same name as the Cell's class. such as `DetailCell` or `ItemCell`, which use  UpperCamelCase.

The Segue's identifier, in another way, is more like a verb when we use them. When we write `if segue.identifier == "showDetail"`, it likely to say: "if we want to _show detail_". So, I always give them names like show{The Content to be shown}, such as `showDetail` or `showItem`.

I'd like to hear other's thought about their styles. :]

**Comment by Jessy-** [comment]
I know I like your cell identifier approach; following that convention can eliminate using strings directly in code. (https://github.com/Catterwaul/HemiprocneMystacea/blob/develop/HemiprocneMystacea/UIKit/dequeuedReusableCell.swift)

I don't have an opinion yet on naming segues. Thanks for your idea; I'll try it out.

**Comment by rayfix** [comment]
I think it is a good recommendation.  I am not sure that we want to get into UIKit patterns but maybe this is one to start with.  Let me sleep on it.

**Comment by rayfix** [comment]
@micpringle Do you think this is in the Style Guide's charter?

**Comment by micpringle** [comment]
@rayfix 

Personally, in these cases I prefer to use static variables. For instance, if I had a `UITableViewCell` subclass named `EpisodeCell`, then I'd add a static variable to that class called `identifier`, which I could then use like so:

`let cell = tableView.dequeueReusableCellWithIdentifier(EpisodeCell.identifier)`

For segue identifiers, I do exactly the same but declare them on the controller instead.

I'm not convinced that the _contents_ of the strings needs to be part of the style guide though.

**Comment by rayfix** [comment]
Thanks for the info, Mic. Spoke with Ray W. about this issue and we decided not to include this guideline in this update.  That doesn't mean it is not useful.  (I might adapt into some my own projects.)
