### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by LightMan** [raywenderlich/swift-style-guide#133]
I am missing the [code organization](https://github.com/raywenderlich/objective-c-style-guide#code-organization) part like the one in the objective-C. I am not talking only about the pragma marks but also about the order of the different sections that appear in a class

I mean something like.

header - license
...
imports
...
# Mark: - Constants
...

class / struct / enum / whatever
# Mark: - IBOutlets
...
# Mark: - Lifecycle
...
# Mark: - Custom Accessors
...
# Mark: - IBActions
...
# Mark: - Public
...
# Mark: - Private
...
# Mark: - Protocol extensions
...

**Comment by behrad-kzm** [comment]
i think thats one of important parts that increase readability of the code ...
thanks for the update

**Comment by rayfix** [comment]
Thanks for the suggestion.  There is mention of breaking your classes into logical extensions and having each one of those extensions begin with a Mark.  I plan to put this into its own section and make it more prominent.  In terms of specific sections to use, I think it is beyond the scope of the RW style guide.
