### ISSUE TITLE
#selector syntax

### ISSUE THREAD

**Issue by icanzilb** [raywenderlich/swift-style-guide#137]
I move that to comply with the rest of the swift style guide which encourages omitting any information that is redundant we include a rule to omit the class name out of selectors, e.g:

**not preferred**:
`#selector(ViewController.viewDidLoad)`

**preferred:**
`#selector(viewDidLoad)`

on the count that not specifying a class name implies the current class, which for tutorials is most often the case. 

@micpringle ?

**Comment by JRG-Developer** [comment]
Have you seen this article, @icanzilb ?

https://medium.com/swift-programming/swift-selector-syntax-sugar-81c8a8b10df3#.kzwwu9no8

This was retweeted by Chris Lattner, so it appears those in-the-know back the idea of private Selector extensions.

I've been using it my projects, and it really makes everything read nicer.

I believe in such case, however, you'd need to specify the full selector, though.

**Comment by icanzilb** [comment]
I've seen this one and I like the idea, though I guess for tutorials or books we'll have to stick to native syntax as to not confuse the readers. I'm also not super excited about the `#` syntax though :)

**Comment by rayfix** [comment]
Approved.  ( @JRG-Developer I like that pattern too but it only really shines when you are using the same selector in multiple locations which is not super common. )

**Comment by rayfix** [comment]
On Apr 25, 2016, at 2:59 AM, Mic Pringle wrote:

... the new section on selectors is a bit confusing. It doesn't explain what a selector is, and when they should be used. I also find the examples a bit confusing. Why are they using extensions? What are the ':' for? Usually you would assign a selector to a variable, or use it when calling an Obj-C method that expects a selector, but netiher of these instances are catered for by the examples in the style guide.

**Comment by rayfix** [comment]
Submitted for your approval @micpringle

**Comment by rayfix** [comment]
I believe this commit resolves the remaining objection.  Reopen if I got it wrong!  :]
