### ISSUE TITLE
syntax to use instead of c-style for loop

### ISSUE THREAD

**Issue by icanzilb** [raywenderlich/swift-style-guide#138]
c-style for loops are getting sacked in Swift 3 and it's a good idea to comply as soon as possible.

swift collection types actually provide a list of their indexes no matter of the index type so I say we should use those across tutorials and books. E.g:

**not preferred**:
`for var i=0;i<items.count;i++ { ..items[i]... }`

**preferred**:
`for i in items.indices { ... items[i] ... }`

@micpringle ?

**Comment by JRG-Developer** [comment]
👍

**Comment by khalidmahmud** [comment]
the new loop looks great 
but for the loop of this type what should be done?
for var i=0;i<items.count; i+= 2 { ..items[i]... }
what are the possible way to implement this in 
for .... in ?

**Comment by yas375** [comment]
@khalidmahmud 

```swift
for i in 0.stride(to: items.count, by: 2) {
    // items[i]
}
```

**Comment by khalidmahmud** [comment]
@yas375 
thanks bro

**Comment by rayfix** [comment]
Approved.  Adding a section about compiler warnings being verboten.  Also will change the current not preferred examples to use a while loop.

**Comment by rayfix** [comment]
Apologies that there might be some noise here. I guess I am learning the github pull request workflow. :)
