### ISSUE TITLE
Generic Types

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#159]
Proposed:

Generic type names should be descriptive and not single letters like `T` and `U`.

**Preferred:**
```swift
struct Stack<Element> {
  // :
}
```

**Not Preferred:**
```swift
struct Stack<T> {
  // :
}

**Comment by RobertGummesson** [comment]
I prefer the traditional `T` where it makes sense. It seems to be common practise, even outside of the world of Swift. As Apple puts it:

> In most cases, type parameters have descriptive names, such as `Key` and `Value` in `Dictionary<Key, Value>` and `Element` in `Array<Element>`, which tells the reader about the relationship between the type parameter and the generic type or function it’s used in. However, **_when there isn’t a meaningful relationship between them, it’s traditional to name them using single letters_** such as `T`, `U`, and `V`, such as `T` in the `swapTwoValues(_:_:)` function above.

**Comment by rayfix** [comment]
Good stuff!  It has been a while since I have read that section in the guide.

How about:

Generic type parameter names should be descriptive, upper camel case. When a type name doesn't have a meaningful relationship or role, use the traditional uppercase single letters such as `T``, `U`, and `V`.

**Preferred:**
```swift
struct Stack<Element> { ... }
func writeTo<Target: OutputStream>(inout target: Target) { ... }
func max<T : Comparable>(x: T, _ y: T) -> T
```

**Not Preferred:**
```swift
struct Stack<T> { ... }
func writeTo<target: OutputStream>(inout t: target) { ... }
func max<Thing : Comparable>(x: Thing, _ y: Thing) -> Thing
```

**Comment by rayfix** [comment]
I think it is resolved.  Comment or reopen if there is something you believe there is something that needs to be fixed w.r.t. this issue.
