### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#162]
Proposed.  Comments appreciated.

**Unused Code**

Unused (dead) code, including Xcode template code and placeholder comments should be removed.  An exception is when your tutorial or book instructs the user to use the commented code.

Aspirational methods not directly associated with the tutorial whose implementation simply calls the super class should also be removed.

**Not Preferred:**
```swift
override func didReceiveMemoryWarning() {
   super.didReceiveMemoryWarning()
  // Dispose of any resources that can be recreated.
}

override func numberOfSectionsInTableView(tableView: UITableView) -> Int {
   // #warning Incomplete implementation, return the number of sections
   return 1
}

override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
  // #warning Incomplete implementation, return the number of rows
  return Database.contacts.count
}

```

**Preferred:**
```swift
override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
  return Database.contacts.count
}
```

**Comment by jawwad** [comment]
On this, I think it might also be useful specifically say "including any empty/unused UIApplicationDelegate methods", or perhaps have one or two of them in the example.

**Comment by rayfix** [comment]
Also considering adding:

Keep imports minimal. Don't import `UIKit` when importing `Foundation` will suffice.
