### ISSUE TITLE
Extending object lifetime

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#165]
Proposed.  I am sure there will not be any controversy here. :]  Comments appreciated!

### Memory Management

Code (even non-production, tutorial demo code) should not create reference cycles. Analyze your object graph and prevent strong cycles with `weak` and `unowned` references.  Alternatively, use value types (`struct`, `enum`) to prevent cycles altogether.

#### Extending object lifetime

Extend object lifetime using the `[weak self]` and `guard let strongSelf = self else { return }` idiom.  `[weak self]` is preferred to `[unowned self]` where it is not immediately obvious that `self` outlives the closure.

```swift
resource.request().onComplete { [weak self] response in
  guard let strongSelf = self else { return }
  let model = strongSelf.updateModel(response)
  strongSelf.updateUI(model)
}
```

**Comment by RobertGummesson** [comment]
Agreed that strong reference cycles should be avoided at all times but.. In the context of a style guide, I wonder if it's really a choice of style?

**Comment by rayfix** [comment]
Thanks for the feedback.  I agree that we should avoid cluttering up the style guide with endless rules 😃 

The style choices I believe are: 
  1. whether or not to use `[weak self]` or `[unowned self]`.  `[weak self]` is preferred despite it being the more expensive runtime choice.  
  2. Whether to extend lifetime or simply use repeated optional unwrapping e.g. `self?.foo` `self?.bar`.  The preference is to extend with `strongSelf`.  
  3. The choice of variable names for `strongSelf` or `strongX` in general.  I have seen `ss`, `this`, and even `self` in backticks (which is purported to work but be a bug).  `strongSelf` was the winner in a few larger projects I analyzed a while back, (aka Almofire, Siesta).

I also worry there might be a tutorial writer who, in their enthusiasm to demonstrate a particular technique in as simple way as possible, gives short shrift to memory correctness.  I have heard a sentiment (by a WWDC attendee, not RW writer) that a leak, if small and not occurring frequently over the lifetime of an app, can just be ignored. 😮 There are problems with that thesis, but I won't go into them here.

**Comment by RobertGummesson** [comment]
Right, now I am with you. I read it as _**when extending object lifetime, do X**_ and didn't see it as a preference over optional unwrapping. I agree with your points though. I occasionally do `self?.doStuff()` but I always extended lifetime in Obj-C and haven't reflected too much over why I don't do the same in Swift.

**Comment by rayfix** [comment]
The main reason I see to extend lifetime as opposed to repeatedly optionally unwrap is if you have operations A,B,C,D you either do all of them or none of them (2 states).  With optional unwrapping there are n+1 states that are possible.

**Comment by RobertGummesson** [comment]
Yep, agreed. That is the better practise (and also why I did it in Objective-C).
