### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by leoderbois** [raywenderlich/swift-style-guide#172]
In Swift 3 the i-- and i++ are deprecated so the "Not Preferred" In Control Flow section is deprecated too !👍🏽

**Comment by rayfix** [comment]
Thanks @leoderbois!  Notice on the update branch which will be merged shortly that I changed the not preferred examples to use `while` and showed some of the more "esoteric" looping examples.  If you could give that branch's version a look over that would be great and then we can close this.

**Comment by rayfix** [comment]
I think this item has been resolved on the update branch that will be merged later this week.  If I am missing something, please feel free to re-open. Thanks!
