### ISSUE TITLE
Constants, Global Constants and Type Properties

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#173]
Mic Pringle  wrote:

... in the Constants section, type properties are referred to as program constants. This is both confusing and incorrect. Global constants, which is what I think is meant in this context, aren't attached to any type, hence them being global. If a constant is to be attached to a type, and needs to be available at the type level rather than instance level, such as that in the given example, then it should be referred to as a type property as this is what Apple calls it: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Properties.html#//apple_ref/doc/uid/TP40014097-CH14-XID_396.

**Comment by rayfix** [comment]
Since our style omits `self` in most cases, it is difficult to distinguish between instance variables and global variables.  Using a type constant mitigates this confusion.

**Comment by rayfix** [comment]
I think this is now resolved.  Thank you for all of the great feedback @micpringle   I think I finally am now using the term "type properties" correctly. :]

**Comment by wsof401** [comment]
I confuse about global function.
I think all the global function can be avoided by using extension without Objective-C
But, I can declared a function in enum, sometimes it helps me clear the scope,and make sure that no unnecessary variable can be alloc
