### ISSUE TITLE
lowerCamelCase for Enum values

### ISSUE THREAD

**Issue by bmunge** [raywenderlich/swift-style-guide#180]
I've yet to see a case where Apple is using lowerCamelCase for enum values. Could you please provide reference for where this standard in the style guide is coming from?

Thanks!

**Comment by JRG-Developer** [comment]
This guideline comes from this [accepted Swift evolution proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md).

Specifically,

> Lowercase enum cases and static properties.

**Comment by bmunge** [comment]
Thank you!
