### ISSUE TITLE
Enumerations example?

### ISSUE THREAD

**Issue by chrislavender** [raywenderlich/swift-style-guide#184]
The example for enumerations states that lowerCamelCase should be used. Then it shows an example where no enumerations would use any capitalized letters. For clarity, is this what's suggested?

    enum WeirdShape {
        case squigglyRectangle
        case smooshySquare
        case fluffyTriangle
        case edgyCircle
    }

**Comment by rayfix** [comment]
Good point!  I guess if we didn't want to be quite as flamboyant (and keep the same line count):

```swift
enum Shape {
  case rectangle
  case square
  case rightTriangle
  case equilateralTriangle
}
```
Also, I see you indented with 4 spaces.  Nice try. :]

**Comment by chrislavender** [comment]
LOL! An honest mistake. That example is much clearer IMO.

**Comment by chrislavender** [comment]
Submitted PR #185 per your suggestion.
