### ISSUE TITLE
Provide a link to Apple Design Guidelines

### ISSUE THREAD

**Issue by sameoldmadness** [raywenderlich/swift-style-guide#190]
> Following the Apple Design Guidelines, abbreviations and initialisms that appear in all uppercase should be uniformly uppercase or lowercase.

Being a complete newbie I was unable to find "Apple Design Guidelines" mentioned in this quote.

It would be handy to have a direct link to it.

**Comment by rayfix** [comment]
Good idea.  (By the way, currently there is a link at the end of the guide.)

**Comment by sameoldmadness** [comment]
Wow, I've completely missed the "reference material on Swift" section.
