### ISSUE TITLE
One line if-else statement

### ISSUE THREAD

**Issue by luki** [raywenderlich/swift-style-guide#193]
I have a question regarding the one liner if statements, as I have not found it mentioned in the guide. Is it okay to be using something like:

``` Swift
var playerMark = player == 1 ? "x" : "o"
```

Thanks!

**Comment by rayfix** [comment]
Personally I am a fan.  I am a little less of a fan of nested ternary one liners.  BTW, I think that should be a `let` :)

**Comment by anatoliyv** [comment]
I prefers to put all ternary operators inside (...). It looks much more readable for me:

```
let playerMark = ( player == 1 ? "x" : "o" )      // let var be let
```

**Comment by Deco354** [comment]
Are there not cases when using this would be bad.
I came across this code in a repo I contribute to and I find this:
`hostNameLabel.text = host.name == nil || (host.name!.isEmpty) ? "DetailsDetails.NoName".localized : host.name`

a lot less readable than this
```
if host.name == nil || host.name!.isEmpty {
  "DetailsDetails.NoName".localized
} else {
  host.name
}
```
