### ISSUE TITLE
Project "organisation"  should be specified

### ISSUE THREAD

**Issue by jrturton** [raywenderlich/swift-style-guide#198]
All RW.com sample projects should probably have an organisation specified, for consistency in bundle identifiers and so on. I realise it doesn't affect the copyright headers since those are covered separately.

**Comment by designatednerd** [comment]
@jrturton Per our non-code style guide, I believe you mean "organization". :trollface:

**Comment by jrturton** [comment]
@designatednerd 🇬🇧 🖕😘

**Comment by rayfix** [comment]
Proposed text.  Section preceding Copyright.

## Organization and Bundle Identifier

Where Xcode is involved, the organization should be set to `Ray Wenderlich` and the Bundle Identifier set to `com.razeware.TutorialName` where `TutorialName` is the name of the tutorial project.
