### ISSUE TITLE
swiftlint.yml 

### ISSUE THREAD

**Issue by casche** [raywenderlich/swift-style-guide#199]
Has anyone created a swiftlint.yml file to enforce this style guide?

**Comment by felipeplets** [comment]
Also looking for it, as I have a team working on apps having the swiftlint.yml for this style guide would enhance a lot code quality and code reviews.

**Comment by piv199** [comment]
+1 why is there still no swiftlint.yml?

**Comment by hollance** [comment]
The cool thing about open source is that *you* can contribute to it. :-)

**Comment by JRG-Developer** [comment]
@piv199 Write one and send a PR! 😉

**Comment by m4rr** [comment]
I also was looking for a [`swift-format`](https://github.com/apple/swift/blob/master/docs/SwiftFormat.md) tool.

**Comment by EtherTyper** [comment]
@casche From the Swift Algorithms Club, also by raywenderlich.com: https://github.com/raywenderlich/swift-algorithm-club/blob/master/.swiftlint.yml

**Comment by haemi** [comment]
function_body_length: 80
function_parameter_count: 8

isn't this too lax? 8 parameters and a method length of 80 seems a lot

**Comment by rcritz** [comment]
In progress. Coming "soon".
