### ISSUE TITLE
lower case enums clash with reserved keywords "public", "private"

### ISSUE THREAD

**Issue by simoami** [raywenderlich/swift-style-guide#207]
https://github.com/raywenderlich/swift-style-guide#enumerations

This rule is difficult to follow if you consider the following definition:

```
enum VisibilityType: String {
    case Private = "private"
    case Friends = "friends"
    case Public = "public"
}
```

**Comment by rayfix** [comment]
Swift evolution has already ruled on this. The whole of UIKit is going to be that way in Swift 3.  Here is a workaround:

```swift
enum Visibility: String {
  case `public`, `private`
}

let v1 = Visibility.public
let v2: Visibility = .private
v1.rawValue
v2.rawValue
```

**Comment by rayfix** [comment]
BTW @simoami thanks for raising the issue though!  Glad you are thinking about this stuff :]

**Comment by simoami** [comment]
Thanks @rayfix 

One last question, how can I easily convert a plain string to one of the enum entries? think of a visibility type coming in a json string

With the previous structure, I could do `VisibilityType(rawValue: visibility)`

**Comment by simoami** [comment]
Also in Swift 2 `let v1 = Visibility.public` throws an error

**Comment by simoami** [comment]
This worked for me:

```
enum Visibility {
    case `public`, `friends`, `private`
    init?(rawValue: String) {
        switch rawValue {
        case "public": self = .`public`
        case "friends": self = .`friends`
        case "private": self = .`private`
        default: return nil
        }
    }
}
```

Also, specifying a value works this way: let v1 = Visibility.`public`

**Comment by rayfix** [comment]
@simoami If you use a Sting backed enum, you don't have to write your own initializer.  At least in Xcode 8 beta 6:

```swift
enum Visibility: String {
  case `public`, `private`, friend
}

let v1 = Visibility(rawValue: "private")  // Optional(Visibility.private)
let v2 = Visibility(rawValue: "friend")   // Optional(Visibility.friend)
let v3 = Visibility(rawValue: "public")   // Optional(Visibility.public)
let v4 = Visibility(rawValue: "haha")     // nil
```

**Comment by simoami** [comment]
That works. Thanks for your help!
