### ISSUE TITLE
Handling Multiple `guard let`s With Same Return

### ISSUE THREAD

**Issue by samfranz** [raywenderlich/swift-style-guide#209]
So I understand how a single line `guard let` should be laid out style wise, but I'm curious on how to handle the situation where the `guard let` spans multiple lines with numerous variables. 

## For example:
```swift
guard let id = restorationIdentifier,
            let controller = storyboard?.instantiateViewControllerWithIdentifier(id) else { return  }
```
```swift
private func saveImage() {
        guard let thumbnail = thumbnail,
              let image = image,
              let imageData = UIImageJPEGRepresentation(image, 0.7),
              let thumbnailData = UIImageJPEGRepresentation(thumbnail, 1.0),
              let imagePath = ASSET_PATH.URLByAppendingPathComponent("image").path,
              let thumbnailPath = ASSET_PATH.URLByAppendingPathComponent("thumbnail").path
            else { return }
        
        imageData.writeToFile(imagePath, atomically: true)
        thumbnailData.writeToFile(thumbnailPath, atomically: true)
    }
```

It's that darn `else { return } `, and I'm not sure if I should have it stick out on it's own, or for it to be included in the last `guard let` line. Not sure if this is the best approach of laying this out, but any direction that can be provided would be dandy. Thank you for reading this and have yourself a great day.

**Comment by rayfix** [comment]
Thanks for the thought.  Others have asked about this.  In my own code I have been doing:

```swift
guard let thumbnail = thumbnail,
           let image = image else {
             return
          }
```
The reason return is off by it's lonesome is that it is easy to put a breakpoint on if you need to.  If the line gets crazy long I could see putting else on its own line but otherwise I put it on the same line.

How do others do this?

**Comment by RobertGummesson** [comment]
I do the same as @rayfix .

**Comment by samfranz** [comment]
Good to know. Thanks for answering this you guys!
