### ISSUE TITLE
Updating Swift Style Guide for Swift 3.0

### ISSUE THREAD

**Issue by eman6576** [raywenderlich/swift-style-guide#213]
Hi,

This is a great style guide for referencing when it comes to write great, clean Swift code and for reviewing pull requests. Recently, Swift 3.0 was released and I know the whole community is working on updating their codebases to match the latest version. Will you be updating your style guide for Swift 3.0 anytime soon. Thanks.

**Comment by AndySoHotRightNow** [comment]
Looking forward to it as well!

**Comment by ed-mejia** [comment]
+1

**Comment by rayfix** [comment]
Thanks!  This work will happen on the swift3 branch and once it is approved by the RW team leads it will merge to master.

**Comment by rayfix** [comment]
Please keep an eye on the swift3 branch.  It is mostly complete and will be merged on Thursday of next week.  If you have issues or suggestions please raise them now! :]

**Comment by NikKovIos** [comment]
func convertPointAt(column column: Int, row: Int) -> CGPoint
browse
"Extraneous duplicate parameter name; 'column' already has an argument label"
