### ISSUE TITLE
CGFloat Type Inferrence

### ISSUE THREAD

**Issue by pixlwave** [raywenderlich/swift-style-guide#217]
This isn't really an issue, I'm just intrigued as to why
`let maximumWidth: CGFloat = 106.5`
is preferred over
`let maximumWidth = CGFloat(106.5)`

**Comment by RobertGummesson** [comment]
It's also what Apple recommends:
let `constant name`: `type` = `expression`

When I look at`CGFloat(106.5)` I see a type cast from Double to CGFloat but perhaps it makes no difference to the compiler.

I personally prefer type inference for consistency reasons:
`let maximumWidth: CGFloat = 106.5`
`let maximumWidth: CGFloat`
`var maximumWidth: CGFloat?`

It can also be more convenient to infer type. Example:
`let colors: [UIColor] = [.red, .green, .blue]`
vs.
`let colors = [UIColor.red, UIColor.green, UIColor.blue]`

**Comment by pixlwave** [comment]
Ok, I can certainly see the logic in this. I guess I only thought it seemed odd as I was looking at consistency from this direction:

`let maximumWidth = CGFloat(106.5)`
`let maximumSize = CGSize(width: 106.5, height: 79.9)`

Very much like your array of colours example 👍🏻

**Comment by hollance** [comment]
Note that `CGFloat(106.5)` isn't really a type-cast. The `106.5` does not have a type until the compiler figures out in what context it is being used.

**Comment by rayfix** [comment]
Thanks for the discussion.  I don't see anything actionable on the style guide here but if I am mistaken please feel free to reopen the issue and clarify.

**Comment by pixlwave** [comment]
Yep, thanks to everyone who responded 🙂
