### ISSUE TITLE
Remove antiquated reference to ++ and -- in correctness section

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#222]
Proposed update:
## Correctness

Consider warnings as errors. This rule informs style decisions such as using a `#selector` types instead of string literals.

**Comment by JRG-Developer** [comment]
👍 

Just some minor grammar changes:

## Correctness

Consider warnings as errors. This rule informs many style decisions such as using `#selector` types instead of string literals.
