### ISSUE TITLE
New line character at the end of file

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#224]
On behalf of @vadimeisenbergibm vadimeisenbergibm committed on GitHub on Jul 18

Added "New line character at the end of file" rule
Rationale:
- A Unix convention
- Part of C language standard, ISO/IEC 9899:TC2   http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf : "A source file that is not empty shall end in a new-line character" 
- Discussion on StackOverflow - http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Proposed change:
- New line character at the end of file.

**Comment by jawwad** [comment]
👍

**Comment by vadimeisenbergibm** [comment]
@rayfix so is it approved? Should I submit a PR for that?

**Comment by rayfix** [comment]
@vadimeisenbergibm  I think it is a good one!  Please submit a PR against the swift3 branch and also add your self to contributors if you choose.  Thanks!

**Comment by rayfix** [comment]
@vadimeisenbergibm I went ahead and added to the swift 3 branch.  Thanks!
