### ISSUE TITLE
Omitting first argument label of function?

### ISSUE THREAD

**Issue by JozefLipovsky** [raywenderlich/swift-style-guide#227]
Hi,
there is a minor typo in the **Naming** section for functions. 
```swift
func dateFromString(dateString: String) -> NSDate
func convertPointAt(column column: Int, row: Int) -> CGPoint
func timedAction(afterDelay delay: NSTimeInterval, perform action: SKAction) -> SKAction!

// would be called like this:
dateFromString("2014-03-14")
convertPointAt(column: 42, row: 13)
timedAction(afterDelay: 1.0, perform: someOtherAction)
```

With current function declaration `func dateFromString(dateString: String) -> NSDate`  it would be called like ` dateFromString(dateString: "2014-03-14")` , not like `dateFromString("2014-03-14")`.

I believe that in this case function was meant to be declared with omitted first argument label, because  _"the context is very clear"_ :
```swift
func dateFromString(_ dateString: String) -> NSDate
...

// would be called like this:
dateFromString("2014-03-14")
...
```

Let me know if I should submit PR, update is [ready](https://github.com/JozefLipovsky/swift-style-guide/commit/bc5a013519319de38b47e3194b05f31c8fe9f7ff) 🙂

**Comment by RobertGummesson** [comment]
It appears that entire section is Swift 2, even on the Swift 3 branch.
`func convertPointAt(column column: Int, row: Int) -> CGPoint`
should be:
`func convertPointAt(column: Int, row: Int) -> CGPoint`

**Comment by rayfix** [comment]
Thanks for the feedback.  This section was replaced completely with a summary of the API design guidelines.  See issue #218  Currently committed to the swift3 branch.  If there are problems with the new section, please let me know.
