### ISSUE TITLE
Style Guide For Unit Testing

### ISSUE THREAD

**Issue by eman6576** [raywenderlich/swift-style-guide#229]
Hi,

Thank you for updating the style guide to use Swift 3.0 . One thing that I noticed is that there aren't any guidelines or best practices when it comes to doing unit tests in this guide. I was wondering if a style guide for doing unit tests in Swift could be placed here with best practices and for dealing with certain issues like trying to test private methods for example. Any insight from the team would be greatly appreciated and will help other developers to write better tests the "Swifty" way. Thanks. :]

**Comment by JRG-Developer** [comment]
IMHO, I think this is out of scope for this style guide.

Reasoning:
- While many teams outside of raywenderlich.com use this style guide  (my company included), its primary purpose is consistency for tutorials, books, etc written for raywenderlich.com. The vast majority of tutorials aren't focused on tests... I'm not saying tests aren't important (I strongly think they are), but they're not the focus of _most_ tutorials.

- "Guidelines for unit testing" could easily grow into an _entire_ style guide in its own right... Adding this as one or more sections to this guide likely won't be sufficient to cover it. Conversely, adding several sections is likely too much for this style guide (it's already fairly long).

If anything, I think this should be a separate style guide that perhaps "extends" this style guide. Whether or not this should be an official RW style guide, I'm not sure.

**Comment by rayfix** [comment]
While I think this is beyond the scope of the style guide, recipes for writing good tests would make for an excellent tutorial.  I will put it down on the wish list.
