### ISSUE TITLE
Section "Classes and Structures" has an error in the example

### ISSUE THREAD

**Issue by rcritz** [raywenderlich/swift-style-guide#239]
In the example definition of a well-styled class definition, the `describe` function references a function called `computeArea()` but defines a function `area()` instead.

I'd also observe that it would be an even better styled class definition if it conformed to `CustomStringConvertible` instead of implementing a `describe` function.

**Comment by rayfix** [comment]
Good catch!  Thanks.

**Comment by rayfix** [comment]
Thanks again. Check out the above commit. If you see problems, feel free to reopen the issue. :]

**Comment by rcritz** [comment]
Looks awesome! :]
