### ISSUE TITLE
Generics: "When a type name doesn't have a meaningful relationship or role" 

### ISSUE THREAD

**Issue by JessyCatterwaul** [raywenderlich/swift-style-guide#240]
Although I'm open to the possibility that a case may exist where it is not true, I've found that a generic placeholder type name always has a meaningful relationship or role. The guide should either provide a case that better demonstrates an absence of meaning, or not make the recommendation to use traditional single uppercase letters. 

The current example:
```swift
func max<T: Comparable>(_ x: T, _ y: T) -> T
```
This is the same as found in [Apple's documentation](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/GenericParametersAndArguments.html).

# Missing Meaning
The role of the generic type in this example is to enforce Swift's `Comparable` protocol, and a relationship between `x` and `y`: that they are of the same type. This specialization of `Comparable` does not require a new name.
```swift
func max<Comparable: Swift.Comparable>(
  _ x: Comparable,
  _ y: Comparable
) -> Comparable
```
That namespacing-for-specialization mechanism solves another issue @rayfix brought up. Instead of utilizing a `Type` suffix…
```swift
func topSpeed<RacerType: Racer>(racer: RacerType) -> Double { … }
```
…namespacing can be used instead.
```swift
func topSpeed<Racer: Module.Racer>(racer: Racer) -> Double { … }
```
_`Module` would be the actual name of the module._
# Types
Swift used to have more `T`, bringing over a convention from other languages. But it hasn't stuck around in the most used places. For example, `Optional`  has moved from `T` to `Wrapped`, and `Array` has gone from `T` to `Element`. The non-standard-library `Result` can be seen in the wild with [`Value`](https://www.cocoawithlove.com/blog/2016/08/21/result-types-part-one.html#the-result-type) instead of [`T`](https://www.natashatherobot.com/swift-generics-box/). 

Note that `T` isn't even used as a prefix, [as is convention elsewhere](https://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx). Instead, the meaningful name after that prefix is what we're seeing in Swift, and what I believe this style guide should be promoting.

# Parameters can suggest too much meaning
Naming parameters induces cognitive load on the coder and forces the reader to mentally map symbols to concepts. It may seem reasonable and automatic to some that `max`'s arguments would be known as `x` and `y`, but look where that thinking leads. This is really in the standard library 😿:
```swift
public func max<T : Comparable>(_ x: T, _ y: T, _ z: T, _ rest: T...) -> T
```
Swift has not standardized conventions to deal with this, and so tackling the problem may be out of the scope of this guide, for now. 

However, while I feel it's early to start formally recommending a standard, here's what I've been using. 
```swift
func max<Comparable: Swift.Comparable>(
  _ comparable0: Comparable,
  _ comparable1: Comparable
) -> Comparable
```
### Rationale
The parameter names are not useful, but are unfortunately required. lowerCamelCasing the name of a type is conventional (`comparable: Comparable`), and the position numbers line up with the shorthand names that we ought to be able to refer to them as, which has as of yet not made its way to functions.
```swift
func makeMax<Comparable: Swift.Comparable>(type: Comparable.Type)
-> (Comparable, Comparable) -> Comparable {
  return {
    // We know we're dealing with two of our local `Comparable`s.
    // Names don't matter. Only ordering matters.
    $0 > $1
    ? $0
    : $1
  }
}

let max = makeMax(type: Int.self)

max(3, 7)
```

**Comment by rayfix** [comment]
Hey.  Thanks for digging into this issue.  

I will say `T` has a long tradition from C++ and D, C#, Delphi.  Probably like anything, if you have used it a lot, it looks very natural.  I have been using `T`s and `U`s for a long time so I thing this might be a case of beauty is in the eye of the beholder.  The Swift.Comparable is a nifty trick.  That said,

```swift
public func max<Comparable : Swift.Comparable>(_ comparable0: Comparable,
   _ comparible1: Comparable, _ comparable3: Comparable, _ restOfComparables: Comparable...) -> Comparable`
```
doesn’t feel like such an improvement to me.  Lot of cognitive load there.  The example you raise as the pinnacle of badness actually reads well to me. Hah.

The standard library seems to go the other way when it comes to type / protocol conflicts.  In the case of `Sequence` they have an `Iterator` associated type that conforms to `IteratorProtocol`  They probably weighed how often an `Iterator` type would be used.

I feel like this is a corner case.  For example, I can't imagine an associated type not having some of expressible role.  I think this rule only comes into play when you are dealing with free functions.   Another one that comes to mind is numericCast.

```swift
public func numericCast<T : _SignedInteger, U : _SignedInteger>(_ x: T) -> U
```

they could be named `From` and `To` I guess. but I don't think it really pays for it self.  Since these are not associated types, they don't form an API that you need to code against.

Love to hear thoughts from others.

PS: From the issue it isn't completely clear to me what actual style guide text you would like to change.  You might want to break that out separately so people are clear what you are proposing as a rule.

**Comment by JessyCatterwaul** [comment]
What I meant to illustrate with
```swift
public func max<T : Comparable>(_ x: T, _ y: T, _ z: T, _ rest: T...) -> T
```
is that the alphabet runs out of letters, making the individual arguments end after an arbitrary three, before moving on to the variadic parameter that should be the only necessary parameter:
```swift
public func max<Comparable: Swift.Comparable>(_ comparables: Comparable...) -> Comparable
```

But my issue is with suggesting that a type name has the possibility of "not having a meaningful relationship or role", without an example that displays such a void. Fortunately, I just found [in issue 159](https://github.com/raywenderlich/swift-style-guide/issues/159), that Apple makes the same suggestion that the guide currently does. And their example is not `max`, but a version of this standard library function:
```swift
public func swap<T>(_ a: inout T, _ b: inout T)
```
I racked my brains for a while and couldn't come up with anything better. I think a good improvement would be to just use this signature as the example in the guide, instead of the current `max`.

That said, I'd personally name the parameters `t0` and `t1`, but that's not important. `a` and `b` are much more okay than `x` and `y` because of how many letters are left to work with. 🙃
#
P.S. I'd do it like this:
```swift
public func numericCast<
  Unconverted: _SignedInteger,
  Converted: _SignedInteger
>(_ unconverted: Unconverted) -> Converted
```

P.P.S. I don't know the rationale behind IteratorProtocol. It seems to me that they could have gone with 
```swift
associatedtype Iterator: Swift.Iterator
```

**Comment by rayfix** [comment]
Do you want to make a PR to swift3 that changes the example to 

```swift
public func swap<T>(_ a: inout T, _ b: inout T)
```

and, perhaps:

```swift
public func swap<Thing>(_ a: inout Thing, _ b: inout Thing) 
```

(also, feel free to add yourself to the credits if you desire.)
