### ISSUE TITLE
Preferred and Not Preferred examples for Use of Self 

### ISSUE THREAD

**Issue by tgblank** [raywenderlich/swift-style-guide#241]
I can see why this may have been left out because it seems too obvious, but for consistency, would it make sense to have Preferred and Not Preferred examples for Use of Self?

### Use of Self

For conciseness, avoid using `self` since Swift does not require it to access an object's properties or invoke its methods.

**Preferred**
```swift
class BoardLocation {
  var row: Int = 0
  var column: Int = 0
  
  func resetLocation() {
    row = 1
    column = 1
  }
  
  func reset() {
    resetLocation()
  }
}
```

**Not Preferred**
```swift
class BoardLocation {
  var row: Int = 0
  var column: Int = 0
  
  func resetLocation() {
    self.row = 1
    self.column = 1
  }
  
  func reset() {
    self.resetLocation()
  }
}
```

Use `self` when required to differentiate between property names and arguments in initializers, and when referencing properties in closure expressions (as required by the compiler):

```swift
class BoardLocation {
  let row: Int, column: Int

  init(row: Int, column: Int) {
    self.row = row
    self.column = column
    
    let closure = {
      print(self.row)
    }
  }
}
```

**Comment by rayfix** [comment]
Thank you for reviewing the style guide and suggesting a way it might be improved.

And I am not sure if having a not-preferred section pays for itself (space wise).  Is this a point of confusion? Actually I am wondering if the current example is paying for itself.  Aside: `resetLocation()` is trying to modify immutables so will never compile.  It also perhaps needs to be a struct so it can compile without an `init()` defined.

Even though I am weighing in against this change, let's keep the issue open to see if there are other +1 opinions.  I can be swayed if other people also think the current text and example is confusing. :]

**Comment by tgblank** [comment]
Sorry for the sloppy copy/paste bugs, I should have checked it closer before commenting :]. I edited the comment enough to make it compile, but it could still use a better example.

I didn't think the current text or example was confusing. It just seemed like up to that point in the document the use of Preferred/Not Preferred was pretty consistent, so this one stood out to me.

I could see where this section, along with some others such as **Semicolons**, could do without examples, as the explanation is pretty clear. On the other hand, there is a certain appeal to having a consistent Preferred/Not Preferred flow as you read through the guide. It makes it very easy to quickly scan down and see the point each section is making without even thinking too much about the explanatory text.

**Comment by msheaver** [comment]
+1

I too agree that the Not preferred section, use consistently, is indeed useful and not just taking up dead space. Not only does it show what is not desirable, it also reinforces the pattern or style that is being portrayed. So yes, it does add value to the guide to have those Not preferred sections.

**Comment by jawwad** [comment]
I do really like consistency, however, in this case, I think it's ok to omit the "Preferred" and "Not Preferred" section in order to avoid the style guide getting too large. In fact I think we can even omit the existing example and just say "Use `self` only when required by the compiler (in closures, or in initializers). In other words, if it compiles without `self` then omit it".

Or maybe the example can be visually clarified by adding comments.

```swift
class BoardLocation {
  let row: Int, column: Int

  init(row: Int, column: Int) {
    // self is required when property names match argument names
    self.row = row
    self.column = column

    // self is required in closures
    let closure = {
      print(self.row)
    }
  }
}
```

**Comment by rayfix** [comment]
The current example is no longer valid in Swift 3 because self is not required in non-escaping closures.  At first I tried to clarify the example but ultimately felt it was not pulling its weight.

I attempted to clarify the text and removed the contrived example.  (If you think it is still not clear, feel free to reopen.)

Great points all around, though. Thanks @tgblank for bringing up the issue.
