### ISSUE TITLE
"Noun methods follow the formX rule for the non-mutating version"

### ISSUE THREAD

**Issue by benmorrow** [raywenderlich/swift-style-guide#249]
In the Swift 3 style guide:

* "verb methods follow the -ed, -ing rule for the non-mutating version"
* "noun methods follow the formX rule for the **non-mutating** version"

If you read these lines as mirroring each other, the first line is correct while the second line is not. In the second line, "non-mutating" should be "mutating" (bolded above).

Here are the examples Apple gives:

| Mutating  | Nonmutating |
| ------------- | ------------- |
| `x.sort()`  | `z = x.sorted()`  |
| `x.append(y)`  | `z = x.appending(y)`  |

| Nonmutating  | Mutating |
| ------------- | ------------- |
| x = y.union(z)  | y.formUnion(z)  |
| j = c.successor(i)  | c.formSuccessor(&i)  |

**Comment by rayfix** [comment]
Another great catch. Dang. :]
