### ISSUE TITLE
The wording of the "Consider warnings to be errors" rule feels ambiguous

### ISSUE THREAD

**Issue by jawwad** [raywenderlich/swift-style-guide#250]
@rayfix - The wording of the "Consider warnings to be errors" rule feels ambiguous. 

Does this mean that code should never have warnings or does this mean that in Xcode the build setting should be set in order to treat warnings as errors. I agree that code should never have warnings but I feel that the "treat warnings as errors" build settings recommendation feels excessive, which I'll elaborate on if that was indeed the intention.

**Comment by rayfix** [comment]
I can see that.  At the time this rule was written, convert warnings to errors didn't exist for Swift.   I made this change:  aaf90e76d8bf956ef819169f69d23a09580ee3d8

If you think further change is necessary feel free to reopen. Thanks again!
