### ISSUE TITLE
addTarget() vs addTarget when referring to addTarget(_:action:)

### ISSUE THREAD

**Issue by jawwad** [raywenderlich/swift-style-guide#252]
In the [method naming section](https://github.com/raywenderlich/swift-style-guide/tree/swift3#prose) it states that if a method name is unambiguous, it can be written without parameters, so the first rule states that `addTarget(_:action:)` can be written as `addTarget()`. To me, the parentheses make it seem like `addTarget()` is an actual method that doesn't take parameters.

I'd like to propose that in the first case the method name be written without parentheses, i.e. "Next, you need to call `addTarget`" so that it's clear to the reader that the method's arguments are intentionally omitted.

**Comment by rayfix** [comment]
I see your point and agree. Do you want to formulate a PR?

**Comment by JessyCatterwaul** [comment]
As the method exists in UIKIt now, I agree with `addTarget ` being ideal.

That said, 
`addTarget(_:action:)` should be changed to the accurate `addTarget(_:action:for:)`, 
and 
`addTarget(_: Any?, action: Selector?)` to `addTarget(_ target: Any?, action: Selector, for controlEvents: UIControlEvents)`, right?

#
I actually argue that the UIKit method is named incorrectly, and should start with `add(target:`, but that's not not for this guide to take on. 😝

**Comment by rayfix** [comment]
Branch needs to merge tonight so I resolved the issue. :]
