### ISSUE TITLE
`guard/else` formatting

### ISSUE THREAD

**Issue by JessyCatterwaul** [raywenderlich/swift-style-guide#260]
I think the guide and its readers would benefit from a definitive guideline on all `guard/else` formatting.

This issue has been brought up before, in [209](https://github.com/raywenderlich/swift-style-guide/issues/209), [210](https://github.com/raywenderlich/swift-style-guide/issues/210), and [212](https://github.com/raywenderlich/swift-style-guide/issues/212). I'm bringing it up again because of recent interest in a definitive answer in the Ray Wenderlich Slack group, and from being inspired by Erica Sadun's [_Swift Style_](https://pragprog.com/book/esswift/swift-style).

The example from Slack, using the current guide's [Golden Path](https://github.com/raywenderlich/swift-style-guide#golden-path) section example, would look like this:
```swift
guard let responseJSON = response.result.value as? [String: AnyObject],
      let results = responseJSON["results"] as? [AnyObject],
      let firstResult = results.first as? [String: AnyObject],
      let info = firstResult["info"] as? [String: AnyObject],
      let imageColors = info["image_colors"] as? [[String: AnyObject]] else {
  print("Invalid color information received from service")
  return
}
```
I think we can do better than this.
## Indentation after `guard`
It looks like the pre-else indentation was chosen because of `let`s lining up with three of our two-space indents. That sort of matching-whitespace-to-get-to-a-symbol's-starting-point pattern isn't found anywhere else. [Functions only get 4 spaces, not 6](https://github.com/raywenderlich/swift-style-guide#function-declarations).

Of course, the reason for using something other than the standard 2-space indent, to begin with, is that the line terminated with `else`, and the line that follows it, have no line break in-between. Ensuring a line break solves that problem…
## Positioning `else`
In [212](https://github.com/raywenderlich/swift-style-guide/issues/212), @rayfix mentions that Apple "put[s] the else in different places in the same function", but I think their styling is consistent.

1. Put `else` at the end of single-line guard statements.
2. Put `else` on a new line, at the same indentation level as its preceding `guard`, when the `guard` statement requires multiple lines.
3. As the RW guide dictates under [Spacing](https://github.com/raywenderlich/swift-style-guide#spacing), _Method braces and other braces (if/else/switch/while etc.) always open on the same line as the statement but close on a new line._

Using that style, we get:
```swift
guard let responseJSON = response.result.value as? [String: AnyObject],
  let results = responseJSON["results"] as? [AnyObject],
  let firstResult = results.first as? [String: AnyObject],
  let info = firstResult["info"] as? [String: AnyObject],
  let imageColors = info["image_colors"] as? [[String: AnyObject]]
else {
  print("Invalid color information received from service")
  return
}
```
I believe that would be fine, but sometimes comments are needed. In those cases, I believe that `guard` should go on its own line: (See the **Mitgating Optional Constipation** section in _Swift Style_ for a similar example.)
```swift
func ƒ(condition: Bool?) {
  guard
    // Bind it
    let condition = condition,
    
    // Check it
    condition,
  
    // Do a real binding instead of this nonsense :]
    let int = Int(condition ? "1" : "2")
  else {
    return
  }
  
  print(int)
}
```
This leads to my personal favorite option, even when no comments are involved:
```swift
guard
  let responseJSON = response.result.value as? [String: AnyObject],
  let results = responseJSON["results"] as? [AnyObject],
  let firstResult = results.first as? [String: AnyObject],
  let info = firstResult["info"] as? [String: AnyObject],
  let imageColors = info["image_colors"] as? [[String: AnyObject]]
else {
  print("Invalid color information received from service")
  return
}
```
I've met too many people who didn't know that `guard` could even be separated from `let`. I think if that were made more known, with our help, we'd see wider adoption of this `guard`-as-heading style.
## Consideration of single-line else?
Unlike `if`, you cannot use guard without `else`. When `guard` was new, I wondered why `else` was even necessary and [got an answer from Chris Lattner](https://forums.developer.apple.com/thread/4857). Deemphasizing the importance of the `else` keyword  by having it at the end of a line is something I'm okay with, but in so doing, three lines are needed in all cases, when two could suffice:
```swift
guard condition else {
  return
}

guard condition
else { return }
```
Although this style leads to a consistency of `else` placement that doesn't depend on how many lines the `guard` portion encompasses, it breaks the [Spacing](https://github.com/raywenderlich/swift-style-guide#spacing) rule. I'm okay with breaking the rule for one-line else clauses, but I'm also okay with keeping consistency with the rule, doing it Apple's way. I just don't really feel like three lines are necessary for this kind of `else`:
```swift
guard
  let powerLevel = powerLevel,
  powerLevel > 9000
else { return }
```
I tried the single-line style for some months and it didn't scale. It's got to be two or three, for me, without a more complex rule about how long the binding can get. 
```swift
guard let responseJSON = response.result.value as? [String: AnyObject] else { return }
```
# Summary of my recommendation
1. Put `else` on a new line, at the same indentation level as `guard`, except in the cases where the `guard` itself is a one-liner, but the `else` is not (see example below).
2. Allow single-line `else` statements.
3. Put `guard` on a line by itself, when it represents a multi-line clause.

```swift
guard singleLineCondition else {
  // some line
  exitScope()
}
```

**Comment by RobertGummesson** [comment]
My preference is still single line guards. As I put it in [#212](https://github.com/raywenderlich/swift-style-guide/issues/212):
> In my opinion, having more terse and readable code outweigh any disadvantage.

The matching-whitespace-to-get-to-a-symbol's-starting-point pattern is in my opinion not a big enough excuse to add the extra line breaks and start working against the Xcode indentation. By that I mean Xcode auto-indents the else by the time you add your first curly bracket. The same is true if you copy paste the code, or re-indent (`ctrl` + `i`).

If you happen to need comments, it can always be put down differently there and then.

Regarding your personal favorite, those arguments would also apply to`if let` statements so I suppose you would do this?

```
if 
  let strongSelf = self,
  condition {
  foo()
}
```

For consistency, would you also do this?

```
if
  conditionA &&
  conditionB {
  foo()  
}
```

**Comment by palttuk** [comment]
heeso_kim@tmon.co.kr
2016년 12월 23일 (금) 12:22, Jessy <notifications@github.com>님이 작성:

**Comment by jstheoriginal** [comment]
I definitely agree with this formatting proposal! It’s how I and my coworkers have been doing it for over a year.

**Comment by emilyvon** [comment]
```swift
guard
  let responseJSON = response.result.value as? [String: AnyObject],
  let results = responseJSON["results"] as? [AnyObject],
  let firstResult = results.first as? [String: AnyObject],
  let info = firstResult["info"] as? [String: AnyObject],
  let imageColors = info["image_colors"] as? [[String: AnyObject]]
else {
  print("Invalid color information received from service")
  return
}
 ```
I always like to use this one because I think it looks really nice, and other ways don't feel right to me :P but this has one big program: I always tend to `cmd+A` then `ctrl+I` and Xcode will add 2 more spaces before `else` with auto indentation and it looks awful. :(

**Comment by lugearma** [comment]
`guard
      let responseJSON = response.result.value as? [String: AnyObject],
      let results = responseJSON["results"] as? [AnyObject],
      let firstResult = results.first as? [String: AnyObject],
      let info = firstResult["info"] as? [String: AnyObject],
      let imageColors = info["image_colors"] as? [[String: AnyObject]] else {
          print("Invalid color information received from service")
          return
      }`

I started to use this way, I think is easy to read and also is easy to put breakpoints any line you want in order to see what the "wrong" condition 😊

**Comment by rcritz** [comment]
@JessyCatterwaul I'm updating the guide for 4.2 and am considering how to incorporate this. I'm really not fond of an opening brace on a line by itself. That's offended me for decades! :)

What I'm leaning towards is to accept the indentation that Xcode provides so as to avoid issues during edits with getting non-compliant formatting from pasting into Xcode or having Xcode re-indent a file. To wit:

```
func check(response: HTTPURLResponse?) throws {
  guard
    let response = response,
    200..<300 ~= response.statusCode
    else {
      throw MyNetworking.serverError
  }
}
```

`else` is on a line by itself but indented at the same level as each condition. Each condition is indented one level from `guard`, which is on a line by itself. The body of the `else` code is indented an additional level.

Can you live with that?

**Comment by JessyCatterwaul** [comment]
@rcritz Given Xcode as it is, I think that's a great compromise!

I don't like the single-line opening brace either but haven't come up with better. Fortunately, I've found that I've had to consider using it very rarely, compared to `guard` statements.

If you come up with a better way to handle this next example, the resulting rule might be able to be applied to if statements with several comma-separated clauses!

```swift
protocol Protocol { }

protocol PAT {
  associatedtype Associatedtype
}

func function<
  Parameter0: PAT,
  Parameter1: PAT,
  Parameter2: PAT,
  Parameter3: PAT
>(
  parameter0: Parameter0,
  parameter1: Parameter1,
  parameter2: Parameter2,
  parameter3: Parameter3
)
where
  Parameter0.Associatedtype: Protocol,
  Parameter1.Associatedtype: Protocol,
  Parameter2.Associatedtype: Protocol,
  Parameter3.Associatedtype: Protocol
{
  // 🦁
  // 🐯
  // 🐻
}
```

**Comment by rcritz** [comment]
@JessyCatterwaul I'm going to punt on your protocol for now, though if I were formatting that for a book, the opening brace would appear at the end of the final clause of the `where` and the actual code would be indented another level. I'm not sure Xcode likes that but that's what I'd do.

I've added this `guard` formatting.
