### ISSUE TITLE
Line Length

### ISSUE THREAD

**Issue by yaroslavbabenko** [raywenderlich/swift-style-guide#261]
What is the maximum line length for Swift? 100 or 120 symbols?

**Comment by yaroslavbabenko** [comment]
@RobertGummesson Thanks!

**Comment by mycroftcanner** [comment]
@RobertGummesson 70 doesn't really make sense with the verbosity of Swift's naming convention.

Google's Swift style limit is 100 characters... and that is still too short for Swift

**Comment by RobertGummesson** [comment]
@mycroftcanner - I was actually just quoting the guideline. Even there it's not a hard rule though. See #233 if you'd like to see the rationale.
