### ISSUE TITLE
Lazy Initialization with a closure -> downside

### ISSUE THREAD

**Issue by iwheelbuy** [raywenderlich/swift-style-guide#262]
Hello. Thanks a lot for your style guide!

There is one issue I want to tell you about. [Lazy initialization](https://github.com/raywenderlich/swift-style-guide#lazy-initialization) where you set a default property value with a closure has some weird impact on other files in the project. I have described it on [stackoverflow](http://stackoverflow.com/questions/41647354/default-property-value-with-closure-makes-a-compiler-to-recompile-all-files). I myself switched to calling private factory methods instead of providing a closure. Any thoughts?

**Comment by RobertGummesson** [comment]
FWIW - I posted an answer to your SO question. Probably better to keep the discussion there.
