### ISSUE TITLE
Abbreviated copyright notice

### ISSUE THREAD

**Issue by fulldecent** [raywenderlich/swift-style-guide#274]
An alternate copyright notice is advocated at http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/

> Copyright [year project started] - [current year], [project founder] and the [project name] contributors.

Please consider accepting this as an alternative to the long form in this style guide.

**Comment by fulldecent** [comment]
Ping. Is this project still accepting contributions?

**Comment by rcritz** [comment]
Yes, it is, though I've just taken over responsibility for it and am starting to work my way through open issues.

As the copyright notice listed here is required in all raywenderlich.com tutorials and books, we won't be making this particular change. Feel free to use whatever copyright form you choose for your own projects.
