### ISSUE TITLE
Alternative for [weak self] guard let strongSelf = self else { return }

### ISSUE THREAD

**Issue by zaitsevyan** [raywenderlich/swift-style-guide#279]
What do you think about using `self` to avoid compiler error about using of reserved word?
```swift
resource.request().onComplete { [weak self] response in
  guard let `self` = self else {
    return
  }
  //self is not optional here. And it doesn't retain global self.
  let model = self.updateModel(response) 
  self.updateUI(model)
}
```

**Comment by EtherTyper** [comment]
@zaitsevyan This has already been addressed. You can assign a value to \`self`, but it doesn't do anything. You need to assign the non-optional value to a new variable. https://github.com/raywenderlich/swift-style-guide/pull/259#issuecomment-267782574
