### ISSUE TITLE
About strongSelf

### ISSUE THREAD

**Issue by Ricardo1980** [raywenderlich/swift-style-guide#280]
I see the guide says:
`guard let strongSelf = self else `
but I would like to note that this is also possible
``guard let `self` = self else``
which is the one I use and I think is easier, and access self in the same way than we do.

**Comment by rayfix** [comment]
It would be really nice if this work but it is doesn't.  It is actually considered a bug by the core team.  (If you search in the issues you can find the reference.)

**Comment by Ricardo1980** [comment]
Really? It is working perfectly in my app.  
I will try to find that. 
If someone has a link, please...

**Comment by EtherTyper** [comment]
@Ricardo1980 Yup, there's already been two issues asking about this. The original: #259

**Comment by Ricardo1980** [comment]
Thanks a lot. Didn't see that.
