### ISSUE TITLE
if statement with multiple let

### ISSUE THREAD

**Issue by drjasonharrison** [raywenderlich/swift-style-guide#283]
How would you format an if statement with multiple let, the Xcode way with strict 4 column indent:

    if let name = json["name"] as? String,
        let coordinatesJSON = json["coordinates"] as? [String: Double],
        let mealsJSON = json["meals"] as? [String]  { 
        return name + " is at " + coordinatesJSON + " eating "  + mealsJSON 
    }

or with alignment of the multiple lets:

    if let name = json["name"] as? String,
       let coordinatesJSON = json["coordinates"] as? [String: Double],
       let mealsJSON = json["meals"] as? [String]  { 
        return name + " is at " + coordinatesJSON + " eating "  + mealsJSON 
    }

And when you have else, stay with the Xcode way

    if something {
        ....
    } else if let name = json["name"] as? String,
       let coordinatesJSON = json["coordinates"] as? [String: Double],
       let mealsJSON = json["meals"] as? [String]  { 
        return name + " is at " + coordinatesJSON + " eating "  + mealsJSON 
    }

Or something that aligns the let's more to the right?

**Comment by hollance** [comment]
I use 2-space indent, which results in this:

```
if let name = json["name"] as? String,
   let coordinatesJSON = json["coordinates"] as? [String: Double],
   let mealsJSON = json["meals"] as? [String]  { 
  return name + " is at " + coordinatesJSON + " eating "  + mealsJSON 
}
```

Not very pretty, but what can you do eh?

**Comment by JessyCatterwaul** [comment]
The first `let` isn't special, so I like it at the same indentation as all other others. What I recommend for `if` and `guard` is the same. (See https://github.com/raywenderlich/swift-style-guide/issues/260)
```swift
if
  let name = json["name"] as? String,
  let coordinatesJSON = json["coordinates"] as? [String: Double],
  let mealsJSON = json["meals"] as? [String]
{
  return "\(name) is at \(coordinatesJSON) eating \(mealsJSON)"
}
```
I'm okay with `else` coming right after a `}` and space, like this:
```swift
if something {
  // codey codey code
} else if
  let name = json["name"] as? String,
  let coordinatesJSON = json["coordinates"] as? [String: Double],
  let mealsJSON = json["meals"] as? [String]
{
  return "\(name) is at \(coordinatesJSON) eating \(mealsJSON)"
}
```
…and that might be better for saving lines in print. But I prefer the breathing room and formatting standardization of keeping `guard`, `if`, and `else` at the same indentation level all the time. (And `else if` doesn't need to be broken up even though it's a combo.)
```swift
if something {
  // codey codey code
}
else if
  let name = json["name"] as? String,
  let coordinatesJSON = json["coordinates"] as? [String: Double],
  let mealsJSON = json["meals"] as? [String]
{
  return "\(name) is at \(coordinatesJSON) eating \(mealsJSON)"
}
```
