### ISSUE TITLE
Use `self` when optionally binding weak self

### ISSUE THREAD

**Issue by philium** [raywenderlich/swift-style-guide#291]
The style guide states the following:

> For optional binding, shadow the original name when appropriate rather than using names like unwrappedView or actualLabel.

However, this guideline is not being followed when unwrapping `weak self`. Since `self` can be shadowed by escaping it with backticks, I propose the following change:

### Extending object lifetime

Extend object lifetime using the `[weak self]` and ``guard let `self` = self else { return }`` idiom. `[weak self]` is preferred to `[unowned self]` where it is not immediately obvious that `self` outlives the closure. Explicitly extending lifetime is preferred to optional unwrapping.

**Preferred**
```swift
resource.request().onComplete { [weak self] response in
  guard let `self` = self else {
    return
  }
  let model = self.updateModel(response)
  self.updateUI(model)
}
```

**Comment by JessyCatterwaul** [comment]
This has actually been discussed quite a bit already.
https://github.com/raywenderlich/swift-style-guide/issues?utf8=✓&q=%60self%60

**Comment by philium** [comment]
Thank you. I wasn't aware of that.
