### ISSUE TITLE
one-off variables

### ISSUE THREAD

**Issue by EricWVGG** [raywenderlich/swift-style-guide#299]
What’s your opinion on…

```
let workingDirectory = DirectoryConfig.detect().workDir
let filePath = [
        workingDirectory + "Public",
        "uploads",
        filename
    ].joined(separator: "/")
let fileUrl = URL(fileURLWithPath: filePath)
let imageData = try Data(contentsOf: fileUrl)
```

vs

```
let imageData = try Data(contentsOf: URL(fileURLWithPath: [
        DirectoryConfig.detect().workDir + "Public",
        "uploads",
        filename
    ].joined(separator: "/")))
```

? All those let's drive me up the wall. I'm probably in the minority on this.

**Comment by elmodos** [comment]
@EricWVGG you are worried about plenty local constants declared in order to load an image data from file.
I'd say if this is the only occasion to load such file it is ok to place this logic in single method. Otherwise I recommend you to compose final image path somewhere in class that is aware of file system structure and finaly use  something next to load image

```swift
let url = DirectoryConfig.detect().workPublicUploadsFileUrl(for: filename)
let imageData = try Data(contentsOf: url)
```

**Comment by EricWVGG** [comment]
… maybe I should have just pseudocoded this question.

```
let foo = GetFooFromSomewhere(on: "herpderp")
let derp = ["junk", "trunk", "dunk"].joined(":")
let someOp = YackittySmack(withFoo: foo, andDerp: derp)
let result = someOpLoader(op: SomeOp)
```
vs
```
let result = someOpLoader(op: YackittySmack(
  withFoo: GetFooFromSomewhere(on: "herpderp"),
  andDerp: ["junk", "trunk", "dunk"].joined(":")
))
```

**Comment by elmodos** [comment]
@EricWVGG in general it is better name each step to make clear what is retrieved from operation instead of makeing cascaded. Well-written code does not require cmments (mostly)
Thus
```swift
let someId = SomeRepo().someGetter()
let someTempFileName = SomeClass.something(someid)
let finalData = self.someMethod(someTempFileName)
```
is easier to read than 
```swift
let finalData = self.someMethod(SomeClass.something(SomeRepo().someGetter())
)
```
Especially in 2-4 weeks

**Comment by rcritz** [comment]
Definitely prefer the "multiple let" approach. It's much more clear and much more self-documenting. That brings it in line with the injunction under **Comments** that "...the code should be as self-documenting as possible."
