### ISSUE TITLE
Could you give me an example to explain what the sentences mean below ?

### ISSUE THREAD

**Issue by SketchK** [raywenderlich/swift-style-guide#311]
Could you give me an example to explain what the sentences mean below ?

> You can define constants on a type rather than on an instance of that type using type properties. 

Thank you very much

**Comment by dskuza** [comment]
Hi SketchK! First time responding for this style guide, so others, please 👍 if I'm correct:

> You can define constants on a type rather than on an instance of that type using type properties.

Preferred:
```swift
struct Square {
  static let numberOfSides = 4
  // ...
}

// Usage
print("A square has \(Square.numberOfSides) sides").
```

Not Preferred:
```swift
struct Square {
  let numberOfSides = 4
  // ...
}

// Usage
let square = Square()
print("A square has (square.numberOfSides) sides")
```

Here, the property `numberOfSides` is preferred to be defined at the type-level (via `static`), versus at the instance-level, as the `numberOfSides` of a square will never change, and should remain constant for all `Square`s.

**Comment by SketchK** [comment]
@dskuza Thank you very much ! 
I see, but why not change the sentence like ?

You can define constants on a type rather than on an instance of that type using **instance** properties.

in your example, i think instance properties is reasonable than type properties, do you think so ?
