### ISSUE TITLE
Clarification of white space needed

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#313]
Currently:

- There should be exactly one blank line between methods to aid in visual clarity and organization. Whitespace within methods should separate functionality, but having too many sections in a method often means you should refactor into several methods.
- There should be no blank lines after an opening brace or before a closing brace.

Proposed:

- There should be **at most** one blank line between methods **and type declarations** to aid in visual clarity and organization. Whitespace within methods should separate functionality, but having too many sections in a method often means you should refactor into several methods.
- There should be no blank lines after an opening brace or before a closing brace.

**Comment by hollance** [comment]
This makes it seem that no blank lines between methods is OK?

**Comment by rayfix** [comment]
I see.  Good point. I am fine going back to exactly there.  My main goal is to include "type declarations" in there so that they aren't collapsed by editors.

**Comment by rcritz** [comment]
@rayfix just to be sure I understand, you want to add _only_ the phrase **and type declarations** as described in your first note above. Is that correct?

**Comment by rcritz** [comment]
@rayfix I'd like to wrap this up. Can you please advise on the question I asked above?

**Comment by rayfix** [comment]
How about:

* There should be one blank line between methods and up to one blank line between type declarations to aid in visual clarity and organization. Whitespace within methods should separate functionality, but having too many sections in a method often means you should refactor into several methods.

**Comment by rayfix** [comment]
cc @rcritz
