### ISSUE TITLE
What is correct name prefix for subclass of UITableView (UICollectionView)

### ISSUE THREAD

**Issue by Igor-Poltavtsev** [raywenderlich/swift-style-guide#324]
Is there some recommendations what form of prefix should be used for UITableView (UICollectionView) - plural or singular? On example:

UsersTableView or UserTableView?
Accordingly: UsersTableViewCell or UserTableViewCell?

**Comment by rcritz** [comment]
No, there isn't a recommendation. It depends entirely on the context in your app.
