### ISSUE TITLE
Array constructor rule is broken

### ISSUE THREAD

**Issue by jrturton** [raywenderlich/swift-style-guide#329]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/2519784/95011711-9863c300-062a-11eb-9ede-3484a6336d51.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/2519784/95011723-b3363780-062a-11eb-9a4d-d9529f9e2edb.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/2519784/95011733-cba65200-062a-11eb-873b-e44e5052e2a3.png">

I've no idea why as the regex seems fine. The rule seems to work OK in other projects or files too.

**Comment by rcritz** [comment]
Be sure you have the `—no-cache` flag in the script. I found the results with custom rules were inconsistent without it.

**Comment by jrturton** [comment]
I do have that set, I’m fairly sure this is a general linter issue rather than some problem with this rule in particular, so I guess we can knock this on the head.
