### ISSUE TITLE
same in Generics

### ISSUE THREAD

**Issue by DeepMissea** [raywenderlich/swift-style-guide#331]
In Generics,
Preferred: 
`func write<Target: OutputStream>(to target: inout Target)`
Not Preferred:
`func write<Target: OutputStream>(to target: inout Target)`

they are same.

**Comment by JessyCatterwaul** [comment]
That is different than what is in the guide, where the second `target` is not capitalized. The relevant part of the guideline is, "upper camel case names".

**Comment by DeepMissea** [comment]
oh! Thanks a lot.
