### ISSUE TITLE
In Multi-line String Literals, string color is different

### ISSUE THREAD

**Issue by DeepMissea** [raywenderlich/swift-style-guide#332]
Multi-line String Literals,

Not Preferred:
`You cannot charge the flux \`
It has a different color. Is there something special ?

**Comment by t12344** [comment]
> Multi-line String Literals,
> 
> 
> 
> Not Preferred:
> 
> `You cannot charge the flux \`
> 
> It has a different color. Is there something special ?

**Comment by rcritz** [comment]
It's a function of how GitHub renders the page. There is no coloring there in the document itself.

**Comment by t12344** [comment]
> Multi-line String Literals,
> 
> 
> 
> Not Preferred:
> 
> `You cannot charge the flux \`
> 
> It has a different color. Is there something special ?
