### ISSUE TITLE
@JessyCatterwaul Right. Word `minimal` is not clear. I don't know owner consider `indirectly import` but I think `minimal` should include that(It can be only my opinion..). How about below change?

### ISSUE THREAD

**Issue by jorgeluisrdz19** [raywenderlich/swift-style-guide#336]
@JessyCatterwaul Right. Word `minimal` is not clear. I don't know owner consider `indirectly import` but I think `minimal` should include that(It can be only my opinion..). How about below change?

### Minimal Imports
Keep imports minimal. Principal below
* Minumal Module Import. **Example:** Don't import `UIKit` when importing `Foundation` will suffice.
* Consider Indirectly Import.

**Preferred:**
```swift
import UIKit
var view: UIVIew
var deviceModels: Array<String>
```
```swift
import Foundation
var deviceModels: Array<String>
```

**Not Preferred:**
```swift
import UIKit
import Foundation
var view: UIVIew
var deviceModels: Array<String>
```
```swift
import UIKit
var deviceModels: Array<String>
```

_Originally posted by @songbongkeun in https://github.com/raywenderlich/swift-style-guide/issues/290#issuecomment-356548849_

**Comment by t12344** [comment]
> @JessyCatterwaul Right. Word `minimal` is not clear. I don't know owner consider `indirectly import` but I think `minimal` should include that(It can be only my opinion..). How about below change?
> 
> 
> 
> 
> 
> ### Minimal Imports
> 
> Keep imports minimal. Principal below
> 
> * Minumal Module Import. **Example:** Don't import `UIKit` when importing `Foundation` will suffice.
> 
> * Consider Indirectly Import.
> 
> 
> 
> **Preferred:**
> 
> ```swift
> 
> import UIKit
> 
> var view: UIVIew
> 
> var deviceModels: Array<String>
> 
> ```
> 
> ```swift
> 
> import Foundation
> 
> var deviceModels: Array<String>
> 
> ```
> 
> 
> 
> **Not Preferred:**
> 
> ```swift
> 
> import UIKit
> 
> import Foundation
> 
> var view: UIVIew
> 
> var deviceModels: Array<String>
> 
> ```
> 
> ```swift
> 
> import UIKit
> 
> var deviceModels: Array<String>
> 
> ```
> 
> 
> 
> _Originally posted by @songbongkeun in https://github.com/raywenderlich/swift-style-guide/issues/290#issuecomment-356548849_
