### ISSUE TITLE
Proposed text.  Section preceding Copyright.

### ISSUE THREAD

**Issue by jorgeluisrdz19** [raywenderlich/swift-style-guide#338]
Proposed text.  Section preceding Copyright.

## Organization and Bundle Identifier

Where an Xcode project is volved, the organization should be set to `Ray Wenderlich` and the Bundle Identifier set to `com.razeware.TutorialName` where `TutorialName` is the name of the tutorial project.

_Originally posted by @rayfix in https://github.com/raywenderlich/swift-style-guide/issues/198#issuecomment-262685219_

**Comment by t12344** [comment]
𝑲 𝑵 𝑵 𝑼 ᵗ
