### ISSUE TITLE
how to write switch statement

### ISSUE THREAD

**Issue by GregDeveaux** [raywenderlich/swift-style-guide#354]
Hello,
how to write switch statement?

because in the Xcode indentation :
```
switch example {
    case 1 :
         add code
    case 2 :
         add code
    default :
         add code
}
```

on the website dev : 
```
switch example {
case 1 :
   add code
case 2 :
    add code
default :
    add code
}
```

Thanks

**Comment by JessyCatterwaul** [comment]
Your first example doesn't use this default setting, in the Text Editing preferences.

<img width="250" alt="Screen Shot 2022-05-26 at 6 26 27 PM" src="https://user-images.githubusercontent.com/8386742/170589718-7cae1a95-b7de-450c-9b27-5fbc449c8424.png">

Lack of indentation felt weird to me, 8 years ago, but I got used to it and now appreciate it.
