### ISSUE TITLE
Golden Path

### ISSUE THREAD

**Issue by JRG-Developer** [raywenderlich/swift-style-guide#63]
To steal from our Objective-C style guide, I propose the inclusion of the **Golden Path** rule in this guide:

### Golden Path

When coding with conditionals, the left hand margin of the code should be the "golden" or "happy" path. That is, don't nest `if` statements. Multiple return statements are OK.

**Preferred:**
    
    func someMethod() {
    
      if someBoolValue == false {
        return
      }
    
      // Do something important
    }

**Not Preferred:**

    func someMethod() {
    
      if someBoolValue == true {
        // Do something important
      }
    }

**Comment by JRG-Developer** [comment]
With the introduction of `guard` in Swift 2.0, I think we should consider adding the Golden Path to our Swift guide.

I think many agree this is a good idea in Swift now and are already following it in their writing.

**Comment by JRG-Developer** [comment]
Also, multiple `guard` / `let` bindings are now allowed by putting a comma between them. :]

**Comment by lukewar** [comment]
I agree. Example from above in Swift 2.0 should look more like this:

```
guard let optional1 = optional1, let optional2 = optional2, let optional3 = optional3 else {
    // handle missing values
    return;
}

// important code is aligned with the left
```

**Comment by rayfix** [comment]
Approved. I will be adding a section about golden path and guard in the style guide.  @lukewar I like your example but ... that semicolon ... 😆

**Comment by lukewar** [comment]
lol, jumping between `Swift` and `ObjC` is harder than one would think :P

**Comment by RobertGummesson** [comment]
How about dropping the `let` duplicates from that example? You guys think they add clarity?

`guard let optional1 = optional1, optional2 = optional2, optional3 = optional3....`

**Comment by JRG-Developer** [comment]
I'm against dropping the `let` duplicates, or at least, making a hard rule there shouldn't be any duplicates.

Reasoning:

(1) If you include a `where` clause, you *must* specify `let` again. For example, this is a problem:

**Not Allowed:**

    func doSomethingWithOptionalNumber(number1: Int?, number2: Int?) {
      
      guard let number1 = number1 where number1 > number2,
        number2 = number2 else {   //  COMPILER ERROR
          print("Number criteria not met!")
          return
      }
      
      // ... here be magic...
    }

(2) If you have a mix of `var` and `let`, it can be unclear what your intentions are if you omit the `let`/`var` specifier:

**Potentially Unclear:**

    guard let number1 = number1,
      var number2 = number2,
      number3 = number3 else { // Did you really mean for this to be `var` or actually `let`?
        return
    }

I'd propose that:

- There should _always_ be a `let`/ `var`, even if redundant.
- Or, the decision should be left up to the tutorial author, depending on context.

**Comment by rayfix** [comment]
Use of var is deprecated (and will be an error in Swift 3) so that argument is out.  Also, if you order correctly you can omit the let with where.

```swift
func doSomethingWithOptionalNumber(number1: Int?, number2: Int?) {
  
  guard let number1 = number1, number2 = number2 where number1 > number2
    else {   //  COMPILER ERROR
      print("Number criteria not met!")
      return
  }
  
  // ... here be magic...
}
```

That said, I understand that a style guide shouldn't be a straight jacket.  While I may elide the `let` from the example, we don't have to necessarily rule on it.

**Comment by JRG-Developer** [comment]
Admittedly, these were contrived examples. 😉 

However, you definitely won't always be able to reorder to get rid of the necessity for the `let`.

Regarding,

> Use of var is deprecated

You can only have `let` variables now?! That's definitely quite a shift to functional programming in Swift! 

😱 😱 🙀  

Jokes aside though, only `var` method parameters are deprecated. You can definitely have `var` in a `guard` statement. Here's an example:

    func addDefaultHeadersTo(headers: [String: String]?) -> [String: String] {
      
      let defaultHeaders = ["AppVersion": "1.0.42",
                            "Who's Awesome?": "Ray Fix"]
      
      guard var headers = headers else {
        return defaultHeaders
      }
      
      for (key, value) in defaultHeaders {
        headers[key] = value
      }
      
      return headers
    }

**Comment by JRG-Developer** [comment]
> That said, I understand that a style guide shouldn't be a straight jacket. While I may elide the let from the example, we don't have to necessarily rule on it.

👍
