### ISSUE TITLE
Using self

### ISSUE THREAD

**Issue by hollance** [raywenderlich/swift-style-guide#7]
While writing Swift code, I catch myself typing `self.propertyName` and `self.method()` a lot. But in Swift (as in C++, C# and Java) using self is not necessary unless you're trying to resolve an ambiguous situation.

I suggest we don't use `self` except for that purpose.

**Comment by kornerr** [comment]
Hi, sorry to reanimate the dead thread.

I'd like to know how are you guys now feeling after ditching `self`? Are you okay now? Were there any particular readability problems?

**Comment by RobertGummesson** [comment]
I've ditched it and never looked back. :)

**Comment by icanzilb** [comment]
The raywenderlich.com books and tutorials have been selfless for 4 years now and nobody has had any specific complaints.
