### ISSUE TITLE
MARK missing end dash

### ISSUE THREAD

**Issue by grosch** [raywenderlich/swift-style-guide#78]
You kinda sorta implemented my MARK suggestion.  For the ones that go above an extension, I think it's important to have the trailing - as well.   If you just do a leading dash, it really looks no different than a comment in the main class, and is hard to read.  Having the trailing dash adds that trailing line, and really calls it out as a separate section in the drop-down.

Did you intentionally leave it out?

**Comment by gregheo** [comment]
If there are silent supporters of the trailing dash, they're not here ;]. We'll stick with this as-is, as it matches the previous Objective-C style for the jump bar too.
