### ISSUE TITLE
Enum options format

### ISSUE THREAD

**Issue by danielgomezrico** [raywenderlich/swift-style-guide#79]
Which one is prefered?

1. CamelCase with first capitalised letter  

`enum Code: Int {
	case HttpResponseMissingParam = -2
}`

2. CamelCase

`enum Code: Int {
	case httpResponseMissingParam = -2
}`

**Comment by ColinEberhardt** [comment]
I'd say the first option, UpperCamelCase, based onto precedent that UIKit enums all use this casing.

**Comment by ColinEberhardt** [comment]
I'm surprised we don't have a section on enums anywhere in the guide!

**Comment by designatednerd** [comment]
*pushes glasses up bridge of nose* I believe that's called [Pascal Case](http://c2.com/cgi/wiki?PascalCase).

**Comment by danielgomezrico** [comment]
Yeah but it will not look weird because for structs its attributes are camel case?

`enum Code: Int { 
    case HttpResponseMissingParam = -2 
}`

`struct Code {
    let httpResponseMissingParam = -2
}`

**Comment by Jessy-** [comment]
Standard enum entries are constants. Constants use camelCase. UIKit doesn't get this right, because it wasn't written for use with Swift.

Associated values require enum subtype definitions, which are closest to initializers. PascalCase for those.

**Comment by danielgomezrico** [comment]
Just for those with initializers?

**Comment by Jessy-** [comment]
That's what I think. I view these things as sub-enums (not nested enums, for which I'd also use PascalCase), in that they both define a type of thing, and have initializer-esque syntax. But I view non-associated enum values as class constants that have extra type safety.

**Comment by danielgomezrico** [comment]
I think that's better to define a common way because will be confusing to use it in a switch and some cases with upper case and others with lower case.

**Comment by Jessy-** [comment]
You say that as if there was one "it", but I think there are two "its".

**Comment by gregheo** [comment]
Well, we have to pick one. Based on our existing site usage, UIKit precedent, and how Swift is implemented (e.g. how optionals work) – UpperCamelCase.
