### ISSUE TITLE
Variable name

### ISSUE THREAD

**Issue by danielgomezrico** [raywenderlich/swift-style-guide#80]
I was just seeing a video in wwdc 2014 and saw a weird variable name, check the image.

![screen shot 2015-01-09 at 10 15 57 am](https://cloud.githubusercontent.com/assets/76348/5681687/9bbdd7cc-97e8-11e4-95c1-dbde652ae2b6.png)

So they want to use _ instead of camel case for variables?

**Comment by designatednerd** [comment]
From what I've seen in sample code from Apple, this is an anomaly. Almost everything else I've seen is in camelCase.

**Comment by ColinEberhardt** [comment]
Also, this isn't Apple's style guide ;-)

**Comment by gregheo** [comment]
Well, it was a talk on debugging after all. Maybe they inserted a typo on purpose ;].
