### ISSUE TITLE
@objc not working as explained.

### ISSUE THREAD

**Issue by aaronrogers** [raywenderlich/swift-style-guide#82]
In the example
`@objc (RWTChicken) class Chicken {`
The Objective-C header will be created like
```
SWIFT_CLASS("RWTChicken")
@interface Chicken
```
So in Objective-C I still have to reference the class as `Chicken`.  Is `RWTChicken` the intended result?

**Comment by marciok** [comment]
When using a Swift class on Objective-C with a custom name you should use the same name as in Swift, on runtime the object will be created with the custom name provided, for example:
```objectice-c 
Chicken *chicken = [Chicken alloc] init];
NSLog("%@", chicken); // < RWTChicken 0x423432>
``` 
I think it was added to the style guide just to make more concise with the Objective-C guide.

More info:
https://github.com/raywenderlich/swift-style-guide/issues/13 
http://petehare.com/adding-obj-c-prefixes-to-swift-class-for-interoperability/
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html

**Comment by aaronrogers** [comment]
I guess it makes sense but it just seems odd as using `@objc` on methods has the opposite effect in that the name provided in `@objc` for a method is the name used in Objective-C.

How does the above help if there's a `Chicken` class in two separate modules referenced in the same Objective-C file?  How does one specify which `Chicken` is to be used?

**Comment by marciok** [comment]
Sorry I didn't understand your question but as an overall what Apple say about specifying name is:

*"... if the name of your Swift class contains a character that isn’t supported by Objective-C, you can provide an alternative name to use in Objective-C..."*

So I'm not sure if we should add a custom name, it doesn't seems that was made for that, if you don't add  it will generate the object with namespace so you don't risk to have a conflict.

**Comment by aaronrogers** [comment]
Ok, my question is:
- I'm using two third party modules.
- Each of these modules have a `Chicken` class.
- I want to reference both in the same Objective-C file.

How does that work?  When I do `[Chicken new]` which module is used?

**Comment by gregheo** [comment]
Our tutorials are all Swift anyway, so you're right to point out the possible confusion here.
