### ISSUE TITLE
Lower case global constants

### ISSUE THREAD

**Issue by Koshub** [raywenderlich/swift-style-guide#89]
Why constant like 
```swift 
private let maximumWidgetCount = 100
```
 is with lower case while enumeration values are Upper? Constant is not a variable. And enumeration value like .SomeValue is not a type.
I propose to name global constant with Upper case. It will be a mark to avoid using global constants. Swift like PHP has a couple of functions in global namespace. It is not very good. We should think about global constants like about some bad thing.

**Comment by jawwad** [comment]
Hi @Koshub. This had already been discussed in issue 74. Please see https://github.com/raywenderlich/swift-style-guide/issues/74 for more info.

**Comment by Koshub** [comment]
Ok. So what is the main reason to write constants with lower camel case?
I think we can use lower camel case in class constants and we shouldn't use global constants.

**Comment by hollance** [comment]
There is nothing bad about global constants. They are constant, so they cannot change.

**Comment by gregheo** [comment]
The style guide has an example of a private constant, which is only local to the file. After discussing options like the `k` prefix and such, the simplest option was just to go with lower-camel case.

**Comment by craiggrummitt** [comment]
I wonder if the style guide should explicitly mention constants in addition to providing an example. Constant naming convention in Swift would be a great issue to put to rest by an explicit mention in a style guide rather than just implied by an example.
