### ISSUE TITLE
Any example of using weak self?

### ISSUE THREAD

**Issue by harryworld** [raywenderlich/swift-style-guide#91]
For example:

```
func anotherFunction(value: String) {
}

myFunction { [weak self] in 
  if let wself = self {
    print(wself.title)
    anotherFunction(wself.property)
  }
}
```

**Comment by gregheo** [comment]
That's definitely the way to specify other-than-strong references for closure expressions. I'm not sure there's any debate on that so it isn't in the style guide – it's not meant to be a complete encyclopedia with every bit of syntax; just on the stuff we argue about. ;]
