### ISSUE TITLE
Protocol Conformance style is not compatible with variables

### ISSUE THREAD

**Issue by Daniesy** [raywenderlich/swift-style-guide#95]
If we have this code:

    protocol Bar{
        var output:String { get set }
    }
    class Foo {
      // class stuff here
    }

    // MARK: - Bar
    extension Foo: Bar {
       var output:String
    }

I get this error: Extensions may not contain stored properties

**Comment by jackwu95** [comment]
Just like categories in ObjC, protocols cannot contain stored properties.

In your example though `output` is a computed property and in fact can be defined inside an extension:

```
// MARK: - Bar
extension Foo: Bar {
  var output:String {
    get {
      return something
    }
    set {
      // Set something
    }
  }
}
```
This will compile.

**Comment by gregheo** [comment]
@jackwu95 has said it all! ;]

Of course you might need a stored property to manage protocol data, but technically you can implement standard Cocoa protocols using extensions with just methods and computed properties.

**Comment by morisk** [comment]
Its just inconvenient to use extensions for protocol conformance. Eventually you will need properties, so you left with this ugly "get/set" or making them global 
````
protocol Bar{
}
class Foo {
  // class stuff here
}

// MARK: - Bar
var myOtherVar:String?
extension Foo: Bar {
   var myVar:String // Error
}
````
