### ISSUE TITLE
Why not make a branch for people who like braces on new lines for clarity?

### ISSUE THREAD

**Issue by danielgindi** [raywenderlich/swift-style-guide#96]

**Comment by hollance** [comment]
This style guide is for how tutorials and books are formatted for raywenderlich.com. In that case, it makes sense to put braces on the same line, to save space.

**Comment by danielgindi** [comment]
Well if the style guide is intended to match a specific site like raywenderlich.com that makes sense :-)
I stumbled upon this repo and thought that it was something generic

**Comment by jackwu95** [comment]
What you're proposing is 2 different style guides.
I'm sure you are free to fork this style guide and create your very own "Swift-style-guide-with-braces-on-new-lines" style guide :]
